# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_agent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schema',
        ),
    ]
