# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import F

import uuid

def before_forwards_func(apps, schema_editor):
    EventType = apps.get_model("configuration", "EventType")
    EventIP = apps.get_model("ip", "EventIP")
    db_alias = schema_editor.connection.alias

    for event in EventIP.objects.using(db_alias).all():
        event_type = event.eventType
        event.eventType_id = uuid.UUID(hex=str(event_type.eventType).zfill(32))
        event.save()

    EventType.objects.using(db_alias).all().update(id=F('eventType'))

class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_delete_schema'),
        ('ip', '0027_auto_20170215_1516'),
    ]

    operations = [
        migrations.RunPython(before_forwards_func),
        migrations.RemoveField(
            model_name='eventtype',
            name='id',
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='eventType',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
