# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 15:07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_defaultcolumnvisible_defaultsorting_defaultvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='entity',
            field=models.CharField(max_length=255, unique=True, verbose_name='entity'),
        ),
        migrations.AlterField(
            model_name='path',
            name='value',
            field=models.CharField(max_length=255, verbose_name='value'),
        ),
    ]
