# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 10:16
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_archivepolicy'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepolicy',
            name='cache_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cache_policy', to='configuration.Path'),
        ),
        migrations.AddField(
            model_name='archivepolicy',
            name='ingest_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingest_policy', to='configuration.Path'),
        ),
    ]
