# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_archivepolicy'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivepolicy',
            name='cache_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.CacheStorage'),
        ),
        migrations.AddField(
            model_name='archivepolicy',
            name='ingest_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.IngestStorage'),
        ),
    ]
