# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-21 12:42
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_auto_20170308_1607'),
        ('configuration', '0009_archivepolicy_receive_extract_sip'),
    ]

    operations = [
    ]
