# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 11:05
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_auto_20170703_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivepolicy',
            name='checksum_algorithm',
            field=models.IntegerField(choices=[(0, 'md5'), (1, 'sha-1'), (2, 'sha-224'), (3, 'sha-256'), (4, 'sha-384'), (5, 'sha-512')], default=1, verbose_name='Checksum algorithm'),
        ),
    ]
