# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 08:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_eventtype_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
