# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 12:49
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0014_eventtype_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
    ]
