# Generated by Django 2.2.2 on 2019-06-19 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('storage', '0035_auto_20190618_1252'),
        ('ip', '0078_auto_20190406_1559'),
        ('configuration', '0016_auto_20190319_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivePolicy',
            new_name='StoragePolicy',
        ),
    ]
