# Generated by Django 2.2.2 on 2019-06-19 08:41

from django.db import migrations, models


def update_storage_policies(apps, schema_editor):
    StorageMethod = apps.get_model("storage", "StorageMethod")

    for storage_method in StorageMethod.objects.all():
        storage_method.storage_policies.add(storage_method.archive_policy)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('storage', '0035_auto_20190618_1252'),
        ('ip', '0078_auto_20190406_1559'),
        ('configuration', '0016_auto_20190319_1334'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArchivePolicy',
            new_name='StoragePolicy',
        ),
        migrations.AddField(
            model_name='storagepolicy',
            name='storage_methods',
            field=models.ManyToManyField(related_name='storage_policies', to='storage.StorageMethod'),
        ),
        migrations.RunPython(update_storage_policies, migrations.RunPython.noop),
    ]
