# Generated by Django 2.0.13 on 2019-05-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0016_auto_20190319_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='category',
            field=models.IntegerField(choices=[(0, 'Information package'), (1, 'Tag'), (2, 'Structure unit')], default=0),
            preserve_default=False,
        ),
    ]
