# Generated by Django 2.0.13 on 2019-05-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_eventtype_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='category',
            field=models.IntegerField(choices=[(0, 'Information package'), (1, 'Delivery')]),
        ),
    ]
