# Generated by Django 2.2.2 on 2019-06-19 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0018_auto_20190619_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagepolicy',
            name='cache_extracted_age',
        ),
        migrations.RemoveField(
            model_name='storagepolicy',
            name='cache_extracted_size',
        ),
        migrations.RemoveField(
            model_name='storagepolicy',
            name='cache_package_age',
        ),
        migrations.RemoveField(
            model_name='storagepolicy',
            name='cache_package_size',
        ),
        migrations.AddField(
            model_name='storagepolicy',
            name='cache_maximum_age',
            field=models.IntegerField(default=0, verbose_name='Maximum age (days) of content before deletion from cache, resets on access'),
        ),
        migrations.AddField(
            model_name='storagepolicy',
            name='cache_minimum_capacity',
            field=models.IntegerField(default=0, verbose_name='Minimum size (bytes) available on cache before deleting content'),
        ),
    ]
