# Generated by Django 3.1.2 on 2021-01-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0024_auto_20200309_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='site',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
