# Generated by Django 3.2.7 on 2022-08-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0025_auto_20210126_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagepolicy',
            name='ingest_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ingest_policy', to='configuration.path'),
        ),
    ]
