# Generated by Django 4.0.8 on 2023-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0027_alter_storagepolicy_checksum_algorithm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagepolicy',
            name='checksum_algorithm',
            field=models.IntegerField(choices=[(0, 'none'), (1, 'MD5'), (2, 'SHA-1'), (3, 'SHA-224'), (4, 'SHA-256'), (5, 'SHA-384'), (6, 'SHA-512')], default=1, verbose_name='Checksum algorithm'),
        ),
    ]
