# Generated by Django 5.0.1 on 2024-01-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0029_alter_storagepolicy_checksum_algorithm'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='logo_middle',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
