# Generated by Django 5.0.6 on 2024-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0031_alter_parameter_id_alter_path_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagepolicy',
            name='information_class',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, verbose_name='Information class'),
        ),
    ]
