# Generated by Django 5.2.6 on 2025-09-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0032_alter_storagepolicy_information_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagepolicy',
            name='index',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='storagepolicy',
            name='policy_stat',
            field=models.BooleanField(default=True, verbose_name='Policy Status'),
        ),
        migrations.AlterField(
            model_name='storagepolicy',
            name='receive_extract_sip',
            field=models.BooleanField(default=True, verbose_name='Extract SIP on receive'),
        ),
    ]
