# Generated by Django 5.2.9 on 2025-12-04 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0033_alter_storagepolicy_index_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagepolicy',
            name='index',
        ),
    ]
