# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('ip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.EventType'),
        ),
    ]
