# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0005_auto_20160831_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='SubmissionAgreement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_packages', to='profiles.SubmissionAgreement'),
        ),
    ]
