# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0006_auto_20160831_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventDateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
