"""
    ESSArch is an open source archiving and digital preservation system

    ESSArch
    Copyright (C) 2005-2019 ES Solutions AB

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.

    Contact information:
    Web - http://www.essolutions.se
    Email - essarch@essolutions.se
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 11:20
from datetime import datetime

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        InformationPackage = apps.get_model("ip", "InformationPackage")
        db_alias = schema_editor.connection.alias

        for ip in InformationPackage.objects.using(db_alias).all():
            try:
                d = datetime.strptime(ip.CreateDate, "%Y-%m-%dT%H:%M:%S.%fZ")
                ip.CreateDate = d.strftime("%Y-%m-%d %H:%M:%S")
            except:
                pass

            try:
                d = datetime.strptime(ip.Startdate, "%Y-%m-%dT%H:%M:%S.%fZ")
                ip.Startdate = d.strftime("%Y-%m-%d %H:%M:%S")
            except:
                pass

            try:
                d = datetime.strptime(ip.Enddate, "%Y-%m-%dT%H:%M:%S.%fZ")
                ip.Enddate = d.strftime("%Y-%m-%d %H:%M:%S")
            except:
                pass

            ip.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0007_auto_20160831_1038'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='informationpackage',
            name='CreateDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='Enddate',
            field=models.DateTimeField(null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='Startdate',
            field=models.DateTimeField(null=True, verbose_name='start date'),
        ),
        migrations.RemoveField(
            model_name='informationpackage',
            name='Producer',
        ),
        migrations.RemoveField(
            model_name='informationpackage',
            name='Status',
        ),
    ]
