# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 11:20
from __future__ import unicode_literals
from datetime import datetime

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        InformationPackage = apps.get_model("ip", "InformationPackage")
        db_alias = schema_editor.connection.alias

        for ip in InformationPackage.objects.using(db_alias).all():
            try:
                d = datetime.strptime(ip.CreateDate, "%Y-%m-%dT%H:%M:%S.%fZ")
                ip.CreateDate = d.strftime("%Y-%m-%d %H:%M:%S")
            except:
                pass

            try:
                d = datetime.strptime(ip.Startdate, "%Y-%m-%dT%H:%M:%S.%fZ")
                ip.Startdate = d.strftime("%Y-%m-%d %H:%M:%S")
            except:
                pass

            try:
                d = datetime.strptime(ip.Enddate, "%Y-%m-%dT%H:%M:%S.%fZ")
                ip.Enddate = d.strftime("%Y-%m-%d %H:%M:%S")
            except:
                pass

            ip.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0007_auto_20160831_1038'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='informationpackage',
            name='CreateDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='Enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='Startdate',
            field=models.DateTimeField(),
        ),
    ]
