# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0008_auto_20160831_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpackage',
            name='Producer',
        ),
    ]
