# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0009_remove_informationpackage_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpackage',
            name='Status',
        ),
    ]
