# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid

def forwards_func(apps, schema_editor):
    InformationPackage = apps.get_model("ip", "InformationPackage")
    db_alias = schema_editor.connection.alias

    for ip in InformationPackage.objects.using(db_alias).all():
        try:
            ip.ArchivalInstitution = uuid.uuid4()
        except:
            pass

        try:
            ip.ArchivistOrganization = uuid.uuid4()
        except:
            pass

        try:
            ip.ArchivalType = uuid.uuid4()
        except:
            pass

        try:
            ip.ArchivalLocation = uuid.uuid4()
        except:
            pass

        ip.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0010_remove_informationpackage_status'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.CreateModel(
            name='ArchivalInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ArchivalInstitution',
            },
        ),
        migrations.CreateModel(
            name='ArchivalLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ArchivalLocation',
            },
        ),
        migrations.CreateModel(
            name='ArchivalType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ArchivalType',
            },
        ),
        migrations.CreateModel(
            name='ArchivistOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ArchivistOrganization',
            },
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='ArchivalInstitution',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_packages', to='ip.ArchivalInstitution'),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='ArchivalLocation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_packages', to='ip.ArchivalLocation'),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='ArchivalType',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_packages', to='ip.ArchivalType'),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='ArchivistOrganization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='information_packages', to='ip.ArchivistOrganization'),
        ),
    ]
