# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-07 09:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ip', '0011_auto_20160901_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpackage',
            name='Locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='informationpackage',
            name='LockedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='informationpackage',
            name='Unlockable',
            field=models.BooleanField(default=False),
        ),
    ]
