# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0012_auto_20160907_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpackage',
            name='Locked',
        ),
        migrations.RemoveField(
            model_name='informationpackage',
            name='LockedBy',
        ),
        migrations.RemoveField(
            model_name='informationpackage',
            name='Unlockable',
        ),
    ]
