# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0014_auto_20160913_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='Enddate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='Startdate',
            field=models.DateTimeField(null=True),
        ),
    ]
