# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0017_remove_informationpackage_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpackage',
            name='ObjectNumItems',
        ),
        migrations.RemoveField(
            model_name='informationpackage',
            name='ObjectSize',
        ),
    ]
