# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0018_auto_20161109_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventip',
            name='eventDetail',
        ),
        migrations.AddField(
            model_name='informationpackage',
            name='ObjectIdentifierValue',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventip',
            name='eventOutcome',
            field=models.IntegerField(choices=[(0, b'Success'), (1, b'Fail')], default=None, null=True),
        ),
    ]
