# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0019_auto_20161122_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventApplication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WorkflowEngine.ProcessTask'),
        ),
    ]
