# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0020_auto_20161124_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='linkingObjectIdentifierValue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ip.InformationPackage'),
        ),
    ]
