# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0022_auto_20161205_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventApplication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='WorkflowEngine.ProcessTask'),
        ),
    ]
