# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0026_auto_20161220_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventType',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='configuration.EventType'),
        ),
    ]
