# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0027_auto_20170215_1516'),
        ('configuration', '0004_auto_20170215_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuration.EventType'),
        ),
    ]
