# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 15:18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0026_auto_20161220_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpackage',
            name='object_num_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informationpackage',
            name='object_size',
            field=models.BigIntegerField(default=0, verbose_name='object size'),
        ),
    ]
