# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0028_auto_20170215_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpackage',
            name='object_num_items',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='informationpackage',
            name='object_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
