# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0030_auto_20170328_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackagerel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
