# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-28 13:45
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0029_auto_20170315_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationpackage',
            options={'ordering': ['id'], 'permissions': (('can_upload', 'Can upload files to IP'), ('set_uploaded', 'Can set IP as uploaded'), ('create_sip', 'Can create SIP'), ('submit_sip', 'Can submit SIP'), ('transfer_sip', 'Can transfer SIP'), ('change_sa', 'Can change SA connected to IP'), ('lock_sa', 'Can lock SA to IP'), ('unlock_profile', 'Can unlock profile connected to IP')), 'verbose_name': 'Information Package'},
        ),
    ]
