# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-24 10:49
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0029_auto_20170223_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackagerel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
