# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 10:22
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0030_auto_20170328_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationpackage',
            options={'ordering': ['id'], 'permissions': (('can_upload', 'Can upload files to IP'), ('set_uploaded', 'Can set IP as uploaded'), ('create_sip', 'Can create SIP'), ('submit_sip', 'Can submit SIP'), ('transfer_sip', 'Can transfer SIP'), ('change_sa', 'Can change SA connected to IP'), ('lock_sa', 'Can lock SA to IP'), ('unlock_profile', 'Can unlock profile connected to IP'), ('can_receive_remote_files', 'Can receive remote files')), 'verbose_name': 'Information Package'},
        ),
    ]
