# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 15:05
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ip', '0031_auto_20170418_1123'),
        ('ip', '0031_auto_20170524_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workarea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_only', models.BooleanField(default=True)),
                ('type', models.IntegerField(choices=[(0, 'ingest'), (1, 'access')], default=0)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workareas', to='ip.InformationPackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
