# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:13
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0031_auto_20170306_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpackage',
            name='information_packages',
        ),
        migrations.AddField(
            model_name='informationpackage',
            name='aic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='information_packages', to='ip.InformationPackage'),
        ),
    ]
