# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:40
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0032_auto_20170306_1213'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='informationpackagerel',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='informationpackagerel',
            name='aic_uuid',
        ),
        migrations.RemoveField(
            model_name='informationpackagerel',
            name='uuid',
        ),
        migrations.DeleteModel(
            name='InformationPackageRel',
        ),
    ]
