# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-09 13:46
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0033_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='information_packages',
            field=models.ManyToManyField(blank=True, related_name='orders', to='ip.InformationPackage'),
        ),
    ]
