# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-03 08:32
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0038_auto_20170608_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='message_digest_algorithm',
            field=models.IntegerField(choices=[(0, 'MD5'), (1, 'SHA-1'), (2, 'SHA-224'), (3, 'SHA-256'), (4, 'SHA-384'), (5, 'SHA-512')], null=True),
        ),
        migrations.AlterField(
            model_name='informationpackagemetadata',
            name='message_digest_algorithm',
            field=models.IntegerField(choices=[(0, 'MD5'), (1, 'SHA-1'), (2, 'SHA-224'), (3, 'SHA-256'), (4, 'SHA-384'), (5, 'SHA-512')], null=True),
        ),
    ]
