# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-18 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0039_auto_20170703_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventApplication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='WorkflowEngine.ProcessTask'),
        ),
    ]
