# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 13:08
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0042_auto_20170718_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workarea',
            options={'permissions': (('move_from_ingest_workarea', 'Can move IP from ingest workarea'), ('move_from_access_workarea', 'Can move IP from access workarea'))},
        ),
    ]
