# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0043_auto_20170817_1508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('prepare_order', 'Can prepare order'),)},
        ),
    ]
