# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-19 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0045_auto_20170831_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workarea',
            name='type',
            field=models.IntegerField(choices=[(0, b'ingest'), (1, b'access')], default=0),
        ),
    ]
