# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-20 15:00
from django.db import migrations, models

def idToUsername(apps, schema_editor):
    EventIP = apps.get_model("ip", "EventIP")
    User = apps.get_model("auth", "User")
    db_alias = schema_editor.connection.alias

    for e in EventIP.objects.using(db_alias).iterator():
        try:
            e.linkingAgentIdentifierValue = User.objects.using(db_alias).get(pk=int(e.linkingAgentIdentifierValue)).username
        except:
            e.linkingAgentIdentifierValue = None

        e.save(update_fields=['linkingAgentIdentifierValue'])

def usernameToId(apps, schema_editor):
    EventIP = apps.get_model("ip", "EventIP")
    User = apps.get_model("auth", "User")
    db_alias = schema_editor.connection.alias

    for e in EventIP.objects.using(db_alias).iterator():
        try:
            e.linkingAgentIdentifierValue = User.objects.using(db_alias).get(username=str(e.linkingAgentIdentifierValue)).pk
        except:
            e.linkingAgentIdentifierValue = None

        e.save(update_fields=['linkingAgentIdentifierValue'])


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0045_auto_20170831_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='linkingAgentIdentifierValue',
            field=models.ForeignKey('auth.User', on_delete=models.SET_NULL, related_name='events', null=True, db_constraint=False),
        ),
        migrations.AlterField(
            model_name='eventip',
            name='linkingAgentIdentifierValue',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(idToUsername, usernameToId),
    ]
