# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-21 11:31
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0048_auto_20170921_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventOutcome',
            field=models.IntegerField(choices=[(0, 'Success'), (1, 'Failure')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='eventip',
            name='linkingAgentIdentifierValue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
