# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-02 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def forwards_func(apps, schema_editor):
    EventIP = apps.get_model("ip", "EventIP")
    db_alias = schema_editor.connection.alias

    i = 1
    for e in EventIP.objects.using(db_alias).all().order_by('eventDateTime').iterator():
        EventIP.objects.using(db_alias).filter(eventIdentifierValue=e.eventIdentifierValue).update(id=i)
        i += 1


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0050_auto_20170925_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventip',
            old_name='id',
            new_name='eventIdentifierValue',
        ),
        migrations.AlterField(
            model_name='eventip',
            name='eventIdentifierValue',
            field=models.UUIDField(primary_key=False, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='eventip',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='eventip',
            name='id',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='eventip',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
