# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 13:56
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0051_auto_20171002_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventip',
            name='linkingAgentRole',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
