# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 11:32
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0054_auto_20171016_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventip',
            options={'ordering': ['eventDateTime', 'id'], 'verbose_name': 'Events related to IP'},
        ),
    ]
