# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-13 15:41
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0059_auto_20171212_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workarea',
            name='successfully_validated',
            field=jsonfield.fields.JSONField(default=None, null=True),
        ),
    ]
