# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 15:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0061_archivalinstitution_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivalinstitution',
            name='country_code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
