# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-12 10:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0062_archivalinstitution_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivistorganization',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
