# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 18:07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0063_archivistorganization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpackage',
            name='appraisal_date',
            field=models.DateTimeField(null=True),
        ),
    ]
