# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-30 15:33
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0070_auto_20180429_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='submission_agreement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='information_packages', to='profiles.SubmissionAgreement'),
        ),
    ]
