# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-11 16:23
from django.db import migrations, models
import django.db.models.deletion


def forward(apps, schema_editor):
    Agent = apps.get_model("ip", "Agent")
    InformationPackage = apps.get_model("ip", "InformationPackage")
    ArchivistOrganization = apps.get_model("ip", "ArchivistOrganization")
    db_alias = schema_editor.connection.alias

    for ip in InformationPackage.objects.using(db_alias).filter(archivist_organization__isnull=False):
        org = ip.archivist_organization
        agent, _ = Agent.objects.using(db_alias).get_or_create(role='ARCHIVIST', type='ORGANIZATION', name=org.name, code=org.code or '')
        ip.agents.add(agent)

    for org in ArchivistOrganization.objects.using(db_alias).all():
        agent, _ = Agent.objects.using(db_alias).get_or_create(role='ARCHIVIST', type='ORGANIZATION', name=org.name, code=org.code or '')


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0071_auto_20180430_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
                ('other_role', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=255)),
                ('other_type', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='AgentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ip.Agent')),
            ],
        ),
        migrations.AddField(
            model_name='informationpackage',
            name='agents',
            field=models.ManyToManyField(related_name='information_packages', to='ip.Agent'),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='informationpackage',
            name='archival_institution',
        ),
        migrations.RemoveField(
            model_name='informationpackage',
            name='archival_location',
        ),
        migrations.RemoveField(
            model_name='informationpackage',
            name='archival_type',
        ),
        migrations.RemoveField(
            model_name='informationpackage',
            name='archivist_organization',
        ),
        migrations.DeleteModel(
            name='ArchivalInstitution',
        ),
        migrations.DeleteModel(
            name='ArchivalLocation',
        ),
        migrations.DeleteModel(
            name='ArchivalType',
        ),
        migrations.DeleteModel(
            name='ArchivistOrganization',
        ),
    ]
