# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-29 12:29
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def forward(apps, schema_editor):
    GroupObjectPermission = apps.get_model("guardian", "GroupObjectPermission")
    UserObjectPermission = apps.get_model("guardian", "UserObjectPermission")
    InformationPackage = apps.get_model("ip", "InformationPackage")
    InformationPackageGroupObjectPermission = apps.get_model("ip", "InformationPackageGroupObjectPermission")
    InformationPackageUserObjectPermission = apps.get_model("ip", "InformationPackageUserObjectPermission")

    db_alias = schema_editor.connection.alias
    ctype = ContentType.objects.get_for_model(InformationPackage).pk
    grp_obj_perms = []
    user_obj_perms = []

    for ip_grp_obj_perm in InformationPackageGroupObjectPermission.objects.using(db_alias).all():
        grp_obj_perm = GroupObjectPermission(group=ip_grp_obj_perm.group, permission=ip_grp_obj_perm.permission,
                                             object_pk=ip_grp_obj_perm.content_object_id, content_type_id=ctype)
        grp_obj_perms.append(grp_obj_perm)

    for ip_user_obj_perm in InformationPackageUserObjectPermission.objects.using(db_alias).all():
        user_obj_perm = UserObjectPermission(user=ip_user_obj_perm.user, permission=ip_user_obj_perm.permission,
                                             object_pk=ip_user_obj_perm.content_object_id, content_type_id=ctype)
        user_obj_perms.append(user_obj_perm)

    GroupObjectPermission.objects.using(db_alias).bulk_create(grp_obj_perms)
    UserObjectPermission.objects.using(db_alias).bulk_create(user_obj_perms)


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0072_auto_20180511_1823'),
    ]

    operations = [
        migrations.RunPython(forward, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='InformationPackageGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='InformationPackageUserObjectPermission',
        ),
    ]
