# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-31 12:13
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0074_informationpackage_sip_objid__sip_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
