# Generated by Django 2.0.13 on 2019-05-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0047_auto_20190523_1115'),
        ('ip', '0077_auto_20181214_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventip',
            name='structure_units',
            field=models.ManyToManyField(limit_choices_to={'structure__is_template': False}, related_name='events', to='tags.StructureUnit'),
        ),
        migrations.AddField(
            model_name='eventip',
            name='tag_versions',
            field=models.ManyToManyField(related_name='events', to='tags.TagVersion'),
        ),
    ]
