# Generated by Django 2.0.13 on 2019-05-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0079_auto_20190529_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tags.Delivery', verbose_name='delivery'),
        ),
        migrations.AlterField(
            model_name='eventip',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tags.Transfer', verbose_name='transfer'),
        ),
    ]
