# Generated by Django 2.0.13 on 2019-05-29 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0079_auto_20190529_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventOutcomeDetailNote',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
