# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0080_auto_20190529_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventOutcomeDetailNote',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
