# Generated by Django 2.2.5 on 2019-09-30 09:12

from django.db import migrations, models
import django.db.models.deletion

def create_temp_order_type(apps, schema_editor):
    OrderType = apps.get_model("ip", "OrderType")
    OrderType.objects.get_or_create(pk=1, defaults={'name': 'temp'})

class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0080_auto_20190529_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'order type',
                'verbose_name_plural': 'order types',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='consign_method',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='family_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='order_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='personal_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(create_temp_order_type, migrations.RunPython.noop),
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ip.OrderType', verbose_name='type'),
            preserve_default=False,
        ),
    ]
