# Generated by Django 2.2.7 on 2019-11-22 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0052_submissionagreementipdata'),
        ('ip', '0083_auto_20191015_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpackage',
            name='submission_agreement_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.SubmissionAgreementIPData'),
        ),
    ]
