# Generated by Django 2.2.8 on 2019-12-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_submissionagreement_policy'),
        ('ip', '0084_informationpackage_submission_agreement_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpackage',
            name='policy',
        ),
    ]
