# Generated by Django 3.0.2 on 2020-01-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0084_informationpackage_submission_agreement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='generation',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
