# Generated by Django 2.2.7 on 2019-12-05 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0084_informationpackage_submission_agreement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='last_changed_local',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationpackagemetadata',
            name='last_changed_local',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
