# Generated by Django 3.0.2 on 2020-01-29 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0085_auto_20200129_1609'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='workarea',
            index_together={('ip', 'read_only')},
        ),
    ]
