# Generated by Django 3.0.3 on 2020-03-12 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0085_remove_informationpackage_policy'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='informationpackage',
            unique_together={('aic', 'generation')},
        ),
    ]
