# Generated by Django 3.0.2 on 2020-01-29 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0086_auto_20200129_1610'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='informationpackage',
            index_together={('state', 'generation', 'aic')},
        ),
    ]
