# Generated by Django 3.0.4 on 2020-04-14 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0086_auto_20200312_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='last_changed_local',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informationpackagemetadata',
            name='last_changed_local',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
