# Generated by Django 3.2.15 on 2022-09-08 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0087_auto_20200414_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create date'),
        ),
    ]
