# Generated by Django 3.0.2 on 2020-01-29 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0087_auto_20200129_1629'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='informationpackage',
            index_together={('state', 'generation', 'aic'), ('generation', 'aic')},
        ),
    ]
