# Generated by Django 3.0.2 on 2020-01-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0088_auto_20200129_1631'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='informationpackage',
            index_together={('state', 'generation', 'aic'), ('generation', 'aic'), ('generation', 'create_date')},
        ),
    ]
