# Generated by Django 3.2.15 on 2022-09-13 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0088_alter_informationpackage_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventIdentifierValue',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
