# Generated by Django 4.0.7 on 2022-11-05 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0089_alter_eventip_eventidentifiervalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventip',
            name='eventIdentifierValue',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
    ]
