# Generated by Django 3.0.2 on 2020-01-29 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0089_auto_20200129_1832'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='informationpackage',
            index_together={('generation', 'create_date'), ('aic', 'generation'), ('state', 'generation', 'aic')},
        ),
    ]
