# Generated by Django 4.0.8 on 2023-01-17 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0092_informationpackageuserobjectpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='state',
            field=models.CharField(db_index=True, max_length=255, verbose_name='state'),
        ),
    ]
