# Generated by Django 4.0.8 on 2023-02-08 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0025_alter_groupgenericobjects_unique_together'),
        ('ip', '0093_alter_informationpackage_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPackageGroupObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip.informationpackage')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essauth.group')),
            ],
            options={
                'abstract': False,
                'unique_together': {('group', 'content_object')},
            },
        ),
    ]
