# Generated by Django 4.1.7 on 2023-03-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0095_alter_informationpackage_content_mets_digest_algorithm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='content_mets_digest_algorithm',
            field=models.IntegerField(choices=[(1, 'MD5'), (2, 'SHA-1'), (3, 'SHA-256'), (4, 'SHA-384'), (5, 'SHA-512')], null=True),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='message_digest_algorithm',
            field=models.IntegerField(choices=[(1, 'MD5'), (2, 'SHA-1'), (3, 'SHA-256'), (4, 'SHA-384'), (5, 'SHA-512')], null=True),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='package_mets_digest_algorithm',
            field=models.IntegerField(choices=[(1, 'MD5'), (2, 'SHA-1'), (3, 'SHA-256'), (4, 'SHA-384'), (5, 'SHA-512')], null=True),
        ),
        migrations.AlterField(
            model_name='informationpackagemetadata',
            name='message_digest_algorithm',
            field=models.IntegerField(choices=[(1, 'MD5'), (2, 'SHA-1'), (3, 'SHA-256'), (4, 'SHA-384'), (5, 'SHA-512')], null=True),
        ),
    ]
