# Generated by Django 4.1.10 on 2023-09-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0097_alter_informationpackage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='object_identifier_value',
            field=models.CharField(max_length=255, unique=True, verbose_name='object_identifier_value'),
        ),
    ]
