# Generated by Django 5.0.1 on 2024-01-16 19:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0099_alter_eventip_eventidentifiervalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='create_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='create date'),
        ),
    ]
