# Generated by Django 5.0.1 on 2024-01-16 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0100_alter_informationpackage_create_date'),
        ('profiles', '0062_auto_20220913_2220'),
        ('tags', '0076_taguserobjectpermission_taggroupobjects_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='informationpackage',
            index=models.Index(fields=['state', 'package_type', 'active', 'archived', 'generation', 'aic_id'], name='ip_informat_state_64a1ca_idx'),
        ),
    ]
