# Generated by Django 5.0.1 on 2024-01-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0101_informationpackage_ip_informat_state_64a1ca_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='end_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='entry_agent_identifier_value',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='entry_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='entry date'),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='label',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='label'),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='start_date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='start date'),
        ),
    ]
