# Generated by Django 5.2.6 on 2025-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0106_alter_informationpackage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='content',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='informationpackage',
            name='start_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='start date'),
        ),
    ]
