# Generated by Django 5.2.13 on 2026-04-15 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0108_alter_informationpackage_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationpackage',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='information_packages', to=settings.AUTH_USER_MODEL, verbose_name='responsible'),
        ),
        migrations.AlterField(
            model_name='workarea',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
