coverage:
  status:
    project:
      default:
        informational: true
      backend:
        informational: true
        flags:
          - backend
    patch:
      default:
        informational: true
comment:
  after_n_builds: 6
