# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 08:00
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ip_list_columns',
            field=picklefield.fields.PickledObjectField(default=['label', 'object_identifier_value', 'responsible', 'create_date', 'state', 'step_state', 'events', 'status', 'delete'], editable=False),
        ),
    ]
