# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 08:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.IntegerField(choices=[(10, 'info'), (20, 'success'), (30, 'warning'), (40, 'error'), (50, 'critical')]),
        ),
    ]
