# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-15 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess.auth', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.IntegerField(choices=[(10, b'info'), (20, b'success'), (30, b'warning'), (40, b'error'), (50, b'critical')]),
        ),
    ]
