# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 18:30
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0006_userprofile_current_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ip_list_columns',
            field=picklefield.fields.PickledObjectField(default=['label', 'object_identifier_value', 'start_date', 'end_date', 'responsible', 'state', 'step_state', 'status', 'filebrowser', 'delete'], editable=False),
        ),
    ]
