# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-08 18:30
from django.db import migrations
import ESSArch_Core.auth.models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0006_userprofile_current_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ip_list_columns',
            field=picklefield.fields.PickledObjectField(default=ESSArch_Core.auth.models.UserProfile.default_ip_list_columns, editable=False),
        ),
    ]
