# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 13:53
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0007_auto_20180208_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ip_list_view_type',
            field=models.CharField(choices=[('aic', 'AIC'), ('ip', 'IP'), ('flat', 'FLAT')], default='ip', max_length=10),
        ),
    ]
