# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess.auth', '0007_auto_20180208_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ip_list_view_type',
            field=models.CharField(choices=[(b'aic', b'AIC'), (b'ip', b'IP')], default=b'ip', max_length=10),
        ),
    ]
