# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-04 12:25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0011_proxygroup_proxyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
