# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-28 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('essauth', '0013_auto_20180411_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGenericObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essauth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMemberRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=255, unique=True)),
                ('label', models.SlugField(blank=True, max_length=255)),
                ('permissions', models.ManyToManyField(related_name='roles', to='auth.Permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='roles',
            field=models.ManyToManyField(related_name='group_memberships', to='essauth.GroupMemberRole'),
        ),
        migrations.AlterUniqueTogether(
            name='groupgenericobjects',
            unique_together=set([('group', 'object_id', 'content_type')]),
        ),
    ]
