# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 16:18
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('essauth', '0014_auto_20180528_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyPermission',
            fields=[
            ],
            options={
                'default_permissions': [],
                'verbose_name': 'permission',
                'proxy': True,
                'verbose_name_plural': 'permissions',
                'indexes': [],
            },
            bases=('auth.permission',),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
    ]
