# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-21 16:16
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0015_proxypermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
