# Generated by Django 2.0.13 on 2019-04-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0017_auto_20190410_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmemberrole',
            options={'permissions': (('assign_groupmemberrole', 'Can assign roles'),), 'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
    ]
