# Generated by Django 2.2.6 on 2019-10-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0019_auto_20191001_1207'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='groupgenericobjects',
            index=models.Index(fields=['content_type', 'object_id'], name='essauth_gro_content_2ec8dd_idx'),
        ),
    ]
