# Generated by Django 3.0.2 on 2020-01-30 14:00

from django.db import migrations
import django.db.models.deletion
import relativity.mptt


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0020_auto_20191013_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='descendants',
            field=relativity.mptt.MPTTDescendants(default=1, from_fields=[], on_delete=django.db.models.deletion.DO_NOTHING, predicate=relativity.mptt.MPTTQ(('left__gt', relativity.mptt.MPTTRef('left')), ('left__lt', relativity.mptt.MPTTRef('right')), ('tree_id', relativity.mptt.MPTTRef('tree_id'))), related_name='ascendants', to='essauth.Group', to_fields=[]),
            preserve_default=False,
        ),
    ]
