# Generated by Django 3.1.2 on 2020-10-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0020_auto_20191013_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='properties',
            field=models.JSONField(blank=True, default=dict, verbose_name='properties'),
        ),
    ]
