# Generated by Django 3.1.2 on 2021-04-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0021_auto_20201014_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='file_browser_view_type',
            field=models.CharField(choices=[('aic', 'AIC'), ('ip', 'IP'), ('flat', 'FLAT')], default='ip', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ip_list_view_type',
            field=models.CharField(choices=[('list', 'list'), ('grid', 'grid')], default='list', max_length=10),
        ),
    ]
