# Generated by Django 4.1.10 on 2023-09-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0025_alter_groupgenericobjects_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmemberrole',
            name='codename',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='codename'),
        ),
        migrations.AlterField(
            model_name='groupmemberrole',
            name='label',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
