# Generated by Django 5.0.3 on 2024-04-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0026_alter_groupmemberrole_codename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='DEFAULT', max_length=10),
        ),
    ]
