# Generated by Django 5.2.17 on 2026-08-19 08:50

import django.db.models.deletion
from django.db import migrations, models


def copy_group_member_roles(apps, schema_editor):
    """
    Copy the existing automatically-created GroupMember.roles M2M
    relationships into the new explicit GroupMemberRoleAssignment model.
    """
    GroupMember = apps.get_model('essauth', 'GroupMember')
    GroupMemberRoleAssignment = apps.get_model(
        'essauth',
        'GroupMemberRoleAssignment',
    )

    # At this point the historical model state still uses the old
    # automatically-created M2M through model.
    old_through = GroupMember._meta.get_field(
        'roles'
    ).remote_field.through

    assignments = []

    for relation in old_through.objects.all().iterator():
        assignments.append(
            GroupMemberRoleAssignment(
                group_member_id=relation.groupmember_id,
                role_id=relation.groupmemberrole_id,
            )
        )

    GroupMemberRoleAssignment.objects.bulk_create(
        assignments,
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('essauth', '0027_alter_userprofile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='is_locally_managed',
            field=models.BooleanField(default=False, verbose_name='locally managed'),
        ),
        migrations.CreateModel(
            name='GroupMemberRoleAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(default=None, null=True, verbose_name='expiration date')),
                ('is_locally_managed', models.BooleanField(default=False, verbose_name='locally managed')),
                ('group_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='role_assignments', to='essauth.groupmember')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='group_member_assignments', to='essauth.groupmemberrole')),
            ],
            options={
                'unique_together': {('group_member', 'role')},
            },
        ),
        migrations.RunPython(
            copy_group_member_roles,
            migrations.RunPython.noop,
        ),

        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql='DROP TABLE IF EXISTS essauth_groupmember_roles',
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='groupmember',
                    name='roles',
                    field=models.ManyToManyField(
                        related_name='group_memberships',
                        through='essauth.GroupMemberRoleAssignment',
                        to='essauth.groupmemberrole',
                        verbose_name='roles',
                    ),
                ),
            ],
        ),
    ]
