# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorageTargets',
            new_name='StorageTarget',
        ),
    ]
