# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 10:55
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_storagemethod_targets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioqueue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='io_queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
