# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 11:17
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_auto_20170315_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemedium',
            name='number_of_mounts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='storagemedium',
            name='used_capacity',
            field=models.BigIntegerField(default=0),
        ),
    ]
