# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-06 20:01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20170405_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ioqueue',
            options={'get_latest_by': 'posted', 'permissions': (('list_IOQueue', 'Can list IOQueue'),)},
        ),
        migrations.RemoveField(
            model_name='ioqueue',
            name='storage_method',
        ),
        migrations.RemoveField(
            model_name='ioqueue',
            name='storage_target',
        ),
    ]
