# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-10 09:41
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_auto_20170406_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioqueue',
            name='storage_method_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.StorageMethodTargetRelation'),
            preserve_default=False,
        ),
    ]
