# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-11 16:01
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20170410_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemedium',
            name='tape_drive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_medium', to='storage.TapeDrive'),
        ),
        migrations.AddField(
            model_name='storagemedium',
            name='tape_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_medium', to='storage.TapeSlot'),
            preserve_default=False,
        ),
    ]
