# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-15 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20170411_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemedium',
            name='tape_slot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='storage_medium', to='storage.TapeSlot'),
        ),
    ]
