# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20170415_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='device',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='robot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='robot',
            name='label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Describing label for the robot'),
        ),
    ]
