# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_auto_20170415_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ioqueue',
            old_name='task_id',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='ioqueue',
            old_name='transfer_task_id',
            new_name='transfer_task',
        ),
    ]
