# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-26 10:48
from __future__ import unicode_literals

from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_auto_20170502_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapedrive',
            name='idle_time',
            field=models.DurationField(default=timedelta(hours=1)),
        ),
    ]
