# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_auto_20170626_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapedrive',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
