# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 14:48
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_auto_20170411_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tapeslot',
            name='medium_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='The id for the medium, e.g. barcode'),
        ),
    ]
