# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-29 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_auto_20170628_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapedrive',
            name='last_change',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
