# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_tapedrive_last_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotqueue',
            name='tape_drive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.TapeDrive'),
        ),
    ]
