# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-05 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_auto_20170704_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='tapedrive',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (20, 'Write'), (100, 'FAIL')], default=20),
        ),
        migrations.AddField(
            model_name='tapeslot',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (20, 'Write'), (100, 'FAIL')], default=20),
        ),
    ]
