# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-12 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_auto_20170705_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ioqueue',
            name='task',
        ),
        migrations.RemoveField(
            model_name='ioqueue',
            name='transfer_task',
        ),
        migrations.AddField(
            model_name='ioqueue',
            name='task_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AddField(
            model_name='ioqueue',
            name='transfer_task_id',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
