# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-14 10:54
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_auto_20170628_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemethod',
            name='archive_policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_methods', to='configuration.ArchivePolicy'),
        ),
        migrations.AlterField(
            model_name='storagemethodtargetrelation',
            name='storage_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_method_target_relations', to='storage.StorageMethod'),
        ),
        migrations.AlterField(
            model_name='storagemethodtargetrelation',
            name='storage_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_method_target_relations', to='storage.StorageTarget'),
        ),
    ]
