# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-24 12:59
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0042_auto_20170718_1650'),
        ('storage', '0022_auto_20170717_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessqueue',
            options={'get_latest_by': 'posted', 'permissions': (('list_accessqueue', 'Can list access queue'),)},
        ),
        migrations.RemoveField(
            model_name='accessqueue',
            name='password',
        ),
        migrations.RemoveField(
            model_name='accessqueue',
            name='req_type',
        ),
        migrations.RemoveField(
            model_name='accessqueue',
            name='req_uuid',
        ),
        migrations.RemoveField(
            model_name='accessqueue',
            name='storage_medium_id',
        ),
        migrations.AddField(
            model_name='accessqueue',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessqueue',
            name='ip',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='access_queues', to='ip.InformationPackage'),
        ),
        migrations.AddField(
            model_name='accessqueue',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accessqueue',
            name='new_ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_queues_new_ip', to='ip.InformationPackage'),
        ),
        migrations.AddField(
            model_name='accessqueue',
            name='package',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accessqueue',
            name='status',
            field=models.IntegerField(blank=True, choices=[(-1, 'Inactive'), (0, 'Pending'), (2, 'Initiate'), (5, 'Progress'), (20, 'Success'), (100, 'FAIL')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='accessqueue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_queues', to=settings.AUTH_USER_MODEL),
        ),
    ]
