# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-01 14:58
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_auto_20170724_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageobject',
            name='content_location_value',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
