# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-18 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0065_auto_20170531_1133'),
        ('storage', '0026_auto_20170824_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioqueue',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WorkflowEngine.ProcessStep'),
        ),
    ]
