# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0028_auto_20171002_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemethod',
            name='containers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storageobject',
            name='container',
            field=models.BooleanField(default=False),
        ),
    ]
