# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-18 08:52
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0029_auto_20180408_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemethod',
            name='containers',
            field=models.BooleanField(default=False, verbose_name='Long-term'),
        ),
    ]
