# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-26 10:58
from django.db import migrations, models

def forward(apps, schema_editor):
    User = apps.get_model("auth", "User")
    StorageMedium = apps.get_model("storage", "StorageMedium")
    db_alias = schema_editor.connection.alias

    for medium in StorageMedium.objects.using(db_alias).all():
        username = User.objects.using(db_alias).get(pk=medium.agent).username
        medium.agent = username
        medium.save()

class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0031_auto_20180418_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemedium',
            name='agent',
            field=models.CharField(max_length=255),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
