# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 10:40
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0033_auto_20180429_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ioqueue',
            name='result',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
