# Generated by Django 2.2.2 on 2019-06-18 10:52

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0034_auto_20190320_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagemethod',
            old_name='status',
            new_name='enabled',
        ),
        migrations.AlterField(
            model_name='storagemethod',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AlterModelOptions(
            name='storagemethodtargetrelation',
            options={'ordering': ['name'], 'verbose_name': 'Storage Method/Target Relation'},
        ),
        migrations.AlterField(
            model_name='accessqueue',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ioqueue',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='robotqueue',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storagemedium',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storageobject',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='ip.InformationPackage', verbose_name='information package'),
        ),
        migrations.AlterField(
            model_name='storageobject',
            name='last_changed_local',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='storageobject',
            name='storage_medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='storage.StorageMedium', verbose_name='medium'),
        ),
        migrations.AlterField(
            model_name='tapedrive',
            name='last_change',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
