# Generated by Django 2.2.2 on 2019-06-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_auto_20190619_1041'),
        ('storage', '0035_auto_20190618_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemethod',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='remote'),
        ),
        migrations.RemoveField(
            model_name='storagemethod',
            name='archive_policy',
        ),
    ]
