# Generated by Django 2.2.2 on 2019-06-19 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0035_auto_20190618_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagemethod',
            old_name='archive_policy',
            new_name='storage_policy',
        ),
    ]
