# Generated by Django 2.2.2 on 2019-06-19 08:48

from django.db import migrations, models
import django.db.models.deletion


def update_storage_policies(apps, schema_editor):
    StorageMethod = apps.get_model("storage", "StorageMethod")

    for storage_method in StorageMethod.objects.all():
        storage_method.storage_policies.add(storage_method.archive_policy)


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0017_auto_20190619_1041'),
        ('storage', '0035_auto_20190618_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemethod',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='remote'),
        ),
        migrations.AddField(
            model_name='storagemethod',
            name='storage_policies',
            field=models.ManyToManyField(related_name='storage_methods', to='configuration.StoragePolicy'),
        ),
        migrations.RunPython(update_storage_policies, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='storagemethod',
            name='archive_policy',
        ),
    ]
