# Generated by Django 2.2.6 on 2019-10-31 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0036_auto_20190619_1048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storagemethodtargetrelation',
            unique_together={('storage_method', 'storage_target')},
        ),
    ]
