# Generated by Django 3.0.3 on 2020-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0037_auto_20191031_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagemethod',
            name='cached',
            field=models.BooleanField(default=True, verbose_name='Cached'),
        ),
    ]
