# Generated by Django 3.0.4 on 2020-04-14 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0038_storagemethod_cached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemedium',
            name='last_changed_local',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storageobject',
            name='last_changed_local',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
