# Generated by Django 3.2.15 on 2022-09-08 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0039_auto_20200414_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageobject',
            name='last_changed_local',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
