# Generated by Django 4.0.7 on 2022-12-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0040_alter_storageobject_last_changed_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotqueue',
            name='robot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='robot_queue', to='storage.robot'),
        ),
        migrations.AlterField(
            model_name='tapedrive',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (20, 'Ok'), (100, 'FAIL')], default=20),
        ),
        migrations.AlterField(
            model_name='tapeslot',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (20, 'Ok'), (100, 'FAIL')], default=20),
        ),
    ]
