# Generated by Django 4.1.8 on 2023-05-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0041_alter_robotqueue_robot_alter_tapedrive_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagetarget',
            name='type',
            field=models.IntegerField(choices=[(200, 'DISK'), (301, 'IBM-LTO1'), (302, 'IBM-LTO2'), (303, 'IBM-LTO3'), (304, 'IBM-LTO4'), (305, 'IBM-LTO5'), (306, 'IBM-LTO6'), (307, 'IBM-LTO7'), (308, 'IBM-LTO8'), (309, 'IBM-LTO9'), (325, 'HP-LTO5'), (326, 'HP-LTO6'), (327, 'HP-LTO7'), (328, 'HP-LTO8'), (329, 'HP-LTO9'), (401, 'HDFS'), (402, 'HDFS-REST')], default=200, verbose_name='Type'),
        ),
    ]
