# Generated by Django 4.1.9 on 2023-06-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0043_alter_robotqueue_req_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemedium',
            name='tape_drive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_medium', to='storage.tapedrive'),
        ),
        migrations.AlterField(
            model_name='storagemedium',
            name='tape_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_medium', to='storage.tapeslot'),
        ),
    ]
