# Generated by Django 4.1.10 on 2023-08-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0044_alter_storagemedium_tape_drive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotqueue',
            name='io_queue_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='storage.ioqueue'),
        ),
        migrations.AlterField(
            model_name='robotqueue',
            name='tape_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.tapedrive'),
        ),
    ]
