# Generated by Django 4.2.11 on 2024-03-04 18:23

from django.db import migrations
import uuid

from django.db.migrations.operations.fields import AlterField
from django.db.models import NOT_PROVIDED
from django.db import models


class AlterField_char32_to_realUUID(AlterField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        to_model = to_state.apps.get_model(app_label, self.model_name)
        if self.allow_migrate_model(schema_editor.connection.alias, to_model):
            from_model = from_state.apps.get_model(app_label, self.model_name)
            from_field = from_model._meta.get_field(self.name)
            cursor = schema_editor.connection.cursor()
            cursor.execute(
                'SELECT COLUMN_TYPE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME=%s and COLUMN_NAME=%s',
                [from_model._meta.db_table, self.name])
            from_field_is_char32 = 'char(32)' in cursor.fetchone()
            mariadb_has_native_uuid_field = schema_editor.connection.features.has_native_uuid_field and \
                schema_editor.connection.mysql_is_mariadb
            if from_field_is_char32 and mariadb_has_native_uuid_field:
                from_field.__class__ = models.fields.CharField
                from_field.db_collation = None
            to_field = to_model._meta.get_field(self.name)
            if not self.preserve_default:
                to_field.default = self.field.default
            schema_editor.alter_field(from_model, from_field, to_field)
            if not self.preserve_default:
                to_field.default = NOT_PROVIDED


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0045_alter_robotqueue_io_queue_entry_and_more'),
    ]

    operations = [
        AlterField_char32_to_realUUID(
            model_name='accessqueue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='ioqueue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='robot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='robotqueue',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='storagemedium',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='storagemethod',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='storagemethodtargetrelation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='storageobject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='storagetarget',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='tapedrive',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        AlterField_char32_to_realUUID(
            model_name='tapeslot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
