# Generated by Django 5.0.9 on 2024-11-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0046_alter_accessqueue_id_alter_ioqueue_id_alter_robot_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tapeslot',
            unique_together={('slot_id', 'robot')},
        ),
        migrations.AlterField(
            model_name='tapeslot',
            name='medium_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='The id for the medium, e.g. barcode'),
        ),
        migrations.AlterUniqueTogether(
            name='tapeslot',
            unique_together={('medium_id', 'robot'), ('slot_id', 'robot')},
        ),
    ]
