# Generated by Django 5.0.14 on 2025-05-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0047_alter_tapeslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemedium',
            name='status',
            field=models.IntegerField(choices=[(0, 'Inactive'), (20, 'Write'), (30, 'Full'), (100, 'FAIL')], db_index=True),
        ),
        migrations.AlterField(
            model_name='storagemethodtargetrelation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Disabled'), (1, 'Enabled'), (2, 'ReadOnly'), (3, 'Migrate')], db_index=True, default=0, verbose_name='Storage target status'),
        ),
    ]
