# Generated by Django 3.1.2 on 2021-08-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessaid',
            name='link',
            field=models.TextField(blank=True, verbose_name='link'),
        ),
    ]
