# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='archiveobject',
            table='ArchiveObject',
        ),
    ]
