# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0002_auto_20160717_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
