# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0005_auto_20160718_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'Step',
            },
        ),
    ]
