# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0006_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='date_done',
            field=models.DateTimeField(null=True, verbose_name='done at'),
        ),
    ]
