"""
    ESSArch is an open source archiving and digital preservation system

    ESSArch
    Copyright (C) 2005-2019 ES Solutions AB

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.

    Contact information:
    Web - http://www.essolutions.se
    Email - essarch@essolutions.se
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 16:22
from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0007_auto_20160718_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='params',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='processtask',
            name='processstep_pos',
            field=models.IntegerField(null=True, verbose_name='ProcessStep position'),
        ),
        migrations.AddField(
            model_name='processtask',
            name='started',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='started at'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='result',
            field=picklefield.fields.PickledObjectField(default=None, editable=False, null=True),
        ),
    ]
