# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-19 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0007_auto_20160718_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preingest.Step')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preingest.Task')),
            ],
        ),
        migrations.AddField(
            model_name='processtask',
            name='params',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='processtask',
            name='processstep_pos',
            field=models.IntegerField(null=True, verbose_name='ProcessStep position'),
        ),
        migrations.AddField(
            model_name='processtask',
            name='started',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='started at'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='result',
            field=picklefield.fields.PickledObjectField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='tasks',
            field=models.ManyToManyField(through='preingest.StepTask', to='preingest.Task'),
        ),
    ]
