# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0008_auto_20160719_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='undone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='processstep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='WorkflowEngine.ProcessStep'),
        ),
    ]
