# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-21 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0009_auto_20160721_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='undo_type',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
