# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0011_processtask_retried'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='task_id',
            field=models.CharField(max_length=255, verbose_name='task id'),
        ),
    ]
