# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0013_auto_20160724_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='attempt',
            field=models.UUIDField(null=True),
        ),
    ]
