# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0014_processtask_attempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='progress',
        ),
    ]
