# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 16:03
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0015_remove_processstep_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='task_set',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
    ]
