# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0016_processstep_task_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='processstep',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='WorkflowEngine.ProcessStep'),
            preserve_default=False,
        ),
    ]
