# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0017_auto_20160725_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processstep',
            old_name='posted',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='processtask',
            old_name='date_done',
            new_name='time_done',
        ),
        migrations.RenameField(
            model_name='processtask',
            old_name='started',
            new_name='time_started',
        ),
    ]
