# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0018_auto_20160725_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='parent_step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_steps', to='preingest.ProcessStep'),
        ),
    ]
