# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0019_processstep_parent_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='waitForParams',
            field=models.BooleanField(default=False),
        ),
    ]
