# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0020_processstep_waitforparams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processtask',
            options={'ordering': ('processstep_pos',)},
        ),
    ]
