# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0022_auto_20160803_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='task_set',
        ),
        migrations.AlterField(
            model_name='processtask',
            name='name',
            field=models.CharField(choices=[('preingest.tasks.ValidateMetadata', b'ValidateMetadata'), ('preingest.tasks.AddPremisToMetsAmdSec', b'AddPremisToMetsAmdSec'), ('preingest.tasks.CreateIPEventsFile', b'CreateIPEventsFile'), ('preingest.tasks.Third', b'Third'), ('preingest.tasks.UploadFile', b'UploadFile'), ('preingest.tasks.CreateTAR', b'CreateTAR'), ('preingest.tasks.Sleepy', b'Sleepy'), ('preingest.tasks.GenerateXML', b'GenerateXML'), ('preingest.tasks.CreatePhysicalModel', b'CreatePhysicalModel'), ('preingest.tasks.Second', b'Second'), ('preingest.tasks.ValidateLogicalPhysical', b'ValidateLogicalPhysical'), ('preingest.tasks.First', b'First')], max_length=255),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='traceback',
            field=models.TextField(blank=True, editable=False, null=True, verbose_name='traceback'),
        ),
    ]
