# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0023_auto_20160804_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
