# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0024_auto_20160805_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='status',
        ),
    ]
