# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0027_auto_20160805_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtask',
            name='task_id',
        ),
        migrations.AddField(
            model_name='processtask',
            name='celery_id',
            field=models.UUIDField(editable=False, null=True, verbose_name='celery id'),
        ),
    ]
