# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0028_auto_20160808_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveobject',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
