# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0029_archiveobject_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='archiveobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='preingest.ArchiveObject'),
        ),
    ]
