# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0030_auto_20160817_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveobject',
            name='checksum',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archiveobject',
            name='checksum_algorithm',
            field=models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA-1'), ('sha224', 'SHA-224'), ('sha256', 'SHA-256'), ('sha384', 'SHA-384'), ('sha512', 'SHA-512')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archiveobject',
            name='filesize',
            field=models.IntegerField(null=True),
        ),
    ]
