# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0032_processstep_parallel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eventIdentifierValue', models.CharField(max_length=36, unique=True)),
                ('eventDateTime', models.DateTimeField(null=True)),
                ('eventDetail', models.CharField(max_length=255)),
                ('eventApplication', models.CharField(max_length=50)),
                ('eventVersion', models.CharField(max_length=45)),
                ('eventOutcome', models.IntegerField(null=True)),
                ('eventOutcomeDetailNote', models.CharField(max_length=1024)),
                ('linkingAgentIdentifierValue', models.CharField(max_length=45)),
                ('archiveObject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='WorkflowEngine.ArchiveObject')),
            ],
            options={
                'db_table': 'Event',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField(null=True)),
                ('desc_sv', models.CharField(max_length=100)),
                ('desc_en', models.CharField(max_length=100)),
                ('localDB', models.IntegerField(null=True)),
                ('externalDB', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'EventType',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='eventType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkflowEngine.EventType'),
        ),
    ]
