"""
    ESSArch is an open source archiving and digital preservation system

    ESSArch Tools for Producer (ETP)
    Copyright (C) 2005-2017 ES Solutions AB

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <http://www.gnu.org/licenses/>.

    Contact information:
    Web - http://www.essolutions.se
    Email - essarch@essolutions.se
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0034_auto_20160818_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventApplication',
            new_name='application',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventDateTime',
            new_name='dateTime',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventDetail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventOutcome',
            new_name='outcome',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventOutcomeDetailNote',
            new_name='outcomeDetailNote',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventType',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventVersion',
            new_name='version',
        ),
    ]
