# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0036_auto_20160819_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='archiveObject',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='submissionAgreement',
        ),
        migrations.AlterField(
            model_name='processstep',
            name='archiveobject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ip.InformationPackage'),
        ),
        migrations.DeleteModel(
            name='ArchiveObject',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='SubmissionAgreement',
        ),
    ]
