# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0038_auto_20160824_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='parent_step_pos',
            field=models.IntegerField(default=0, verbose_name='Parent step position'),
        ),
    ]
