# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0040_auto_20160825_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='processstep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='WorkflowEngine.ProcessStep'),
        ),
    ]
