# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 13:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0041_auto_20160825_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='params',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
