# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 09:36
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0043_auto_20160831_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='result_params',
            field=jsonfield.fields.JSONField(default={}, null=True),
        ),
    ]
