# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0044_auto_20160916_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='name',
            field=models.CharField(choices=[('WorkflowEngine.tasks.ValidateMetadata', b'ValidateMetadata'), ('WorkflowEngine.tasks.AddPremisToMetsAmdSec', b'AddPremisToMetsAmdSec'), ('WorkflowEngine.tasks.CreateIPEventsFile', b'CreateIPEventsFile'), ('WorkflowEngine.tasks.Third', b'Third'), ('WorkflowEngine.tasks.PrepareIP', b'PrepareIP'), ('WorkflowEngine.tasks.CreateTAR', b'CreateTAR'), ('WorkflowEngine.tasks.UploadFile', b'UploadFile'), ('WorkflowEngine.tasks.Sleepy', b'Sleepy'), ('WorkflowEngine.tasks.GenerateXML', b'GenerateXML'), ('WorkflowEngine.tasks.CreatePhysicalModel', b'CreatePhysicalModel'), ('WorkflowEngine.tasks.Second', b'Second'), ('WorkflowEngine.tasks.CreateIPRootDir', b'CreateIPRootDir'), ('WorkflowEngine.tasks.CreateEvent', b'CreateEvent'), ('WorkflowEngine.tasks.ValidateLogicalPhysical', b'ValidateLogicalPhysical'), ('WorkflowEngine.tasks.First', b'First')], max_length=255),
        ),
    ]
