# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preingest', '0044_auto_20160916_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='name',
            field=models.CharField(choices=[('preingest.tasks.ValidateMetadata', b'ValidateMetadata'), ('preingest.tasks.AddPremisToMetsAmdSec', b'AddPremisToMetsAmdSec'), ('preingest.tasks.CreateIPEventsFile', b'CreateIPEventsFile'), ('preingest.tasks.Third', b'Third'), ('preingest.tasks.PrepareIP', b'PrepareIP'), ('preingest.tasks.CreateTAR', b'CreateTAR'), ('preingest.tasks.UploadFile', b'UploadFile'), ('preingest.tasks.Sleepy', b'Sleepy'), ('preingest.tasks.GenerateXML', b'GenerateXML'), ('preingest.tasks.CreatePhysicalModel', b'CreatePhysicalModel'), ('preingest.tasks.Second', b'Second'), ('preingest.tasks.CreateIPRootDir', b'CreateIPRootDir'), ('preingest.tasks.CreateEvent', b'CreateEvent'), ('preingest.tasks.ValidateLogicalPhysical', b'ValidateLogicalPhysical'), ('preingest.tasks.First', b'First')], max_length=255),
        ),
    ]
