# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0015_auto_20160915_0913'),
        ('preingest', '0047_auto_20160925_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='information_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ip.InformationPackage'),
        ),
    ]
