# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-18 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0048_processtask_information_package'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processstep',
            options={'ordering': ('parent_step_pos', 'time_created')},
        ),
        migrations.AlterModelOptions(
            name='processtask',
            options={'ordering': ('processstep_pos', 'time_started')},
        ),
    ]
