# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 10:16
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0049_auto_20161118_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtask',
            name='traceback',
        ),
        migrations.AddField(
            model_name='processtask',
            name='einfo',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True, verbose_name='einfo'),
        ),
    ]
