# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-12 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0052_processtask_responsible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='waitForParams',
        ),
    ]
