# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 18:51
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0053_remove_processstep_waitforparams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='result_params',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
