# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-10 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0055_remove_processtask_celery_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processtask',
            options={},
        ),
    ]
