# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 13:41
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0055_remove_processtask_celery_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtask',
            name='attempt',
        ),
    ]
