# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-13 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def before_forwards_func(apps, schema_editor):
    ProcessTask = apps.get_model("WorkflowEngine", "ProcessTask")
    db_alias = schema_editor.connection.alias

    ProcessTask.objects.using(db_alias).all().update(retried=None, undone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0057_remove_processtask_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='retried',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='undone',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.RunPython(before_forwards_func),
        migrations.AlterField(
            model_name='processtask',
            name='retried',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retried_task', to='WorkflowEngine.ProcessTask'),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='undone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='undone_task', to='WorkflowEngine.ProcessTask'),
        ),
    ]
