# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0058_auto_20170213_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
