# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-23 09:09
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0059_processtask_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='eager',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='processtask',
            name='eager',
            field=models.BooleanField(default=True),
        ),
    ]
