# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 13:02
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0061_auto_20170223_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtask',
            name='einfo',
        ),
        migrations.AddField(
            model_name='processtask',
            name='exception',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processtask',
            name='traceback',
            field=models.TextField(blank=True),
        ),
    ]
