# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 09:33
from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0064_processtask_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='args',
            field=picklefield.fields.PickledObjectField(default=list, editable=False),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='params',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='result_params',
            field=picklefield.fields.PickledObjectField(default=dict, editable=False),
        ),
    ]
