# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 16:44
from django.db import migrations, models
import django.db.models.deletion


def get_root(step):
    if step.parent_step is None:
        return step

    return get_root(step.parent_step)


def setInformationPackage(apps, schema_editor):
    ProcessTask = apps.get_model("WorkflowEngine", "ProcessTask")
    db_alias = schema_editor.connection.alias

    for t in ProcessTask.objects.using(db_alias).filter(information_package__isnull=True).iterator():
        if t.processstep is None:
            # we have no idea what IP this task belongs to, we can delete it
            t.delete()
            continue

        root_step = get_root(t.processstep)

        if root_step.information_package is None:
            # we have no idea what IP this task belongs to, we can delete it
            t.delete()
            continue

        t.information_package = root_step.information_package
        t.save(update_fields=['information_package'])


def nothing(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0065_auto_20170531_1133'),
    ]

    operations = [
        migrations.RunPython(setInformationPackage, nothing),
        migrations.AlterField(
            model_name='processtask',
            name='information_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip.InformationPackage'),
        ),
    ]
