# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-10-03 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0067_auto_20170925_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processtask',
            options={'get_latest_by': 'time_created', 'ordering': ('processstep_pos', 'time_created'), 'permissions': (('can_run', 'Can run tasks'), ('can_undo', 'Can undo tasks'), ('can_retry', 'Can retry tasks'))},
        ),
    ]
