# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 12:24
from django.db import migrations, models


def forward(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    ProcessTask = apps.get_model("WorkflowEngine", "ProcessTask")
    ProcessTask.objects.using(db_alias).filter(label="").update(label=models.F('name'))


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0067_auto_20170925_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(forward, migrations.RunPython.noop),
    ]
