# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-27 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0068_auto_20171003_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
