# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-13 11:29
from django.db import migrations, models
import django.db.models.deletion
import mptt
import mptt.fields
import mptt.managers


def rebuild_step_mptt(apps, schema_editor):
    manager = mptt.managers.TreeManager()
    ProcessStep = apps.get_model("WorkflowEngine", "ProcessStep")
    manager.model = ProcessStep
    mptt.register(ProcessStep, parent_attr='parent_step')
    manager.contribute_to_class(ProcessStep, 'objects')
    manager.rebuild()


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0071_auto_20180801_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processstep',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processstep',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processstep',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processstep',
            name='parent_step',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_steps', to='WorkflowEngine.ProcessStep'),
        ),
        migrations.RunPython(rebuild_step_mptt, migrations.RunPython.noop),
    ]
