# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-15 12:32
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0072_auto_20180813_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='context',
            field=models.JSONField(default={}, null=True),
        ),
    ]
