# Generated by Django 2.2.2 on 2019-06-27 11:42

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0073_processstep_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='exception',
            field=picklefield.fields.PickledObjectField(default=None, editable=False, null=True),
        ),
    ]
