# Generated by Django 2.2.2 on 2019-06-28 11:08

from django.db import migrations, models
import uuid


def set_celery_id(apps, schema_editor):
    ProcessStep = apps.get_model("WorkflowEngine", "ProcessStep")
    ProcessTask = apps.get_model("WorkflowEngine", "ProcessTask")

    ProcessStep.objects.all().update(celery_id=models.F('id'))
    ProcessTask.objects.all().update(celery_id=models.F('id'))


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0074_auto_20190627_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='celery_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='processtask',
            name='celery_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(set_celery_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='processstep',
            name='celery_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='celery_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
