# Generated by Django 2.2.4 on 2019-08-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0075_auto_20190628_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='allow_failure',
            field=models.BooleanField(default=False),
        ),
    ]
