# Generated by Django 2.2.5 on 2019-09-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0076_auto_20190807_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='run_if',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='hidden',
            field=models.BooleanField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='hidden',
            field=models.BooleanField(db_index=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='on_error',
            field=models.ManyToManyField(to='WorkflowEngine.ProcessTask'),
        ),
    ]
