# Generated by Django 2.2.7 on 2019-12-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0077_auto_20190924_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='reference',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='processtask',
            unique_together={('reference', 'processstep')},
        ),
    ]
