# Generated by Django 3.0.2 on 2020-01-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0084_informationpackage_submission_agreement_data'),
        ('WorkflowEngine', '0078_auto_20191206_1631'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='processtask',
            index=models.Index(fields=['undo_type', 'undone', 'retried', 'processstep', 'information_package'],
                               name='ProcessTask_retried_1_idx'),
        ),
    ]
