# Generated by Django 3.0.2 on 2020-01-27 17:29

from django.db import migrations, models
import django.db.models.deletion
import relativity.mptt


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0078_auto_20191206_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='descendants',
            field=relativity.mptt.MPTTDescendants(default=1, from_fields=[], on_delete=django.db.models.deletion.DO_NOTHING, predicate=relativity.mptt.MPTTQ(('left__gt', relativity.mptt.MPTTRef('left')), ('left__lt', relativity.mptt.MPTTRef('right')), ('tree_id', relativity.mptt.MPTTRef('tree_id'))), related_name='ascendants', to='WorkflowEngine.ProcessStep', to_fields=[]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processstep',
            name='subtree',
            field=relativity.mptt.MPTTSubtree(default=1, from_fields=[], on_delete=django.db.models.deletion.DO_NOTHING, predicate=relativity.mptt.MPTTQ(('left__gte', relativity.mptt.MPTTRef('left')), ('left__lt', relativity.mptt.MPTTRef('right')), ('tree_id', relativity.mptt.MPTTRef('tree_id'))), related_name='rootpath', to='WorkflowEngine.ProcessStep', to_fields=[]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processtask',
            name='status',
            field=models.CharField(choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], db_index=True, default='PENDING', max_length=50, verbose_name='state'),
        ),
    ]
