# Generated by Django 3.0.2 on 2020-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0079_auto_20200127_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtask',
            name='progress',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
