# Generated by Django 3.0.4 on 2020-04-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0086_auto_20200312_1128'),
        ('WorkflowEngine', '0079_auto_20200131_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processtask',
            options={'get_latest_by': 'time_created', 'ordering': ('processstep_pos', 'time_created'), 'permissions': (('can_run', 'Can run tasks'), ('can_revoke', 'Can revoke tasks'), ('can_retry', 'Can retry tasks'))},
        ),
        migrations.AlterIndexTogether(
            name='processtask',
            index_together={('retried', 'processstep', 'information_package')},
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='undo_type',
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='undone',
        ),
    ]
