# Generated by Django 3.1.2 on 2020-10-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0080_auto_20200408_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='context',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
