# Generated by Django 4.0.7 on 2022-12-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0081_auto_20201014_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='processstep',
            name='queue',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processtask',
            name='queue',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
