# Generated by Django 3.0.2 on 2020-01-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0081_auto_20200127_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
