# Generated by Django 4.1.10 on 2023-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0083_processstep_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='hidden',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='hidden',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
    ]
