# Generated by Django 4.2.5 on 2023-10-04 12:48

from django.db import migrations
import mptt
import mptt.fields
import mptt.managers


def rebuild_step_mptt(apps, schema_editor):
    manager = mptt.managers.TreeManager()
    ProcessStep = apps.get_model("WorkflowEngine", "ProcessStep")
    manager.model = ProcessStep
    mptt.register(ProcessStep, parent_attr='parent')
    manager.contribute_to_class(ProcessStep, 'objects')
    manager.rebuild()


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0084_alter_processstep_hidden_alter_processtask_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='processstep',
            options={'get_latest_by': 'time_created', 'ordering': ('parent_pos', 'time_created')},
        ),
        migrations.RenameField(
            model_name='processstep',
            old_name='parent_step',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='processstep',
            old_name='parent_step_pos',
            new_name='parent_pos',
        ),
        migrations.RunPython(rebuild_step_mptt, migrations.RunPython.noop),
    ]
