# Generated by Django 3.0.2 on 2020-01-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0084_informationpackage_submission_agreement_data'),
        ('WorkflowEngine', '0084_auto_20200127_2153'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='processstep',
            index_together={('tree_id', 'lft'), ('tree_id', 'lft', 'rght', 'information_package')},
        ),
    ]
