# Generated by Django 3.0.2 on 2020-01-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0084_informationpackage_submission_agreement_data'),
        ('WorkflowEngine', '0085_auto_20200129_1524'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='processtask',
            index_together={('undo_type', 'undone', 'retried', 'processstep', 'information_package'), ('status', 'information_package')},
        ),
    ]
