# Generated by Django 5.0.14 on 2025-05-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0087_alter_processstep_celery_id_alter_processstep_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processstep',
            name='type',
        ),
        migrations.AddField(
            model_name='processstep',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='processstep',
            name='part_root',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='processstep',
            name='run_state',
            field=models.CharField(blank=True, choices=[('FAILURE', 'FAILURE'), ('PENDING', 'PENDING'), ('RECEIVED', 'RECEIVED'), ('RETRY', 'RETRY'), ('REVOKED', 'REVOKED'), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS')], db_index=True, max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
