# Generated by Django 5.2.14 on 2026-06-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0088_remove_processstep_type_processstep_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processstep',
            name='queue',
            field=models.CharField(blank=True, default='celery', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='queue',
            field=models.CharField(blank=True, default='celery', max_length=255, null=True),
        ),
    ]
