# Generated by Django 5.2.5 on 2025-08-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0088_remove_processstep_type_processstep_label_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='processtask',
            name='ProcessTask_retried_2_idx',
        ),
    ]
