# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='templatePackage',
            fields=[
                ('structure', models.TextField()),
                ('elements', models.TextField()),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
    ]
