# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='finishedTemplate',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('template', jsonfield.fields.JSONField(null=True)),
                ('form', jsonfield.fields.JSONField(null=True)),
                ('data', jsonfield.fields.JSONField(null=True)),
            ],
        ),
    ]
