# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 07:01
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('templateMaker', '0002_finishedtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepackage',
            name='tempates',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='templatepackage',
            name='elements',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='templatepackage',
            name='structure',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
