# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0003_auto_20160830_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatepackage',
            old_name='elements',
            new_name='allElements',
        ),
        migrations.RenameField(
            model_name='templatepackage',
            old_name='structure',
            new_name='existingElements',
        ),
        migrations.RenameField(
            model_name='templatepackage',
            old_name='tempates',
            new_name='treeData',
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='isTreeCreated',
            field=models.BooleanField(default=True),
        ),
    ]
