# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0004_auto_20160831_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepackage',
            name='generated',
            field=models.BooleanField(default=False),
        ),
    ]
