# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0005_templatepackage_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatepackage',
            name='isTreeCreated',
        ),
        migrations.RemoveField(
            model_name='templatepackage',
            name='treeData',
        ),
    ]
