# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0006_auto_20160902_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='finishedTemplate',
        ),
        migrations.RemoveField(
            model_name='templatepackage',
            name='generated',
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='namespace',
            field=models.CharField(default=b'', max_length=20),
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='root_element',
            field=models.CharField(default=b'', max_length=55),
        ),
    ]
