# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0007_auto_20160908_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='extensionPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namespace', models.CharField(max_length=255)),
                ('allElements', jsonfield.fields.JSONField(null=True)),
                ('existingElements', jsonfield.fields.JSONField(null=True)),
                ('allAttributes', jsonfield.fields.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='extensions',
            field=models.ManyToManyField(to='ProfileMaker.extensionPackage'),
        ),
    ]
