# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templateMaker', '0008_auto_20160929_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extensionpackage',
            old_name='namespace',
            new_name='targetNamespace',
        ),
        migrations.RemoveField(
            model_name='templatepackage',
            name='namespace',
        ),
        migrations.AddField(
            model_name='extensionpackage',
            name='prefix',
            field=models.CharField(default='prefix', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extensionpackage',
            name='schemaURL',
            field=models.URLField(default='schemaurl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='prefix',
            field=models.CharField(default='prefix', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='schemaURL',
            field=models.URLField(default='schemaURL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='targetNamespace',
            field=models.CharField(default='targetNamespace', max_length=255),
            preserve_default=False,
        ),
    ]
