"""
    ESSArch is an open source archiving and digital preservation system

    ESSArch
    Copyright (C) 2005-2019 ES Solutions AB

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.

    Contact information:
    Web - http://www.essolutions.se
    Email - essarch@essolutions.se
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 09:59
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0008_auto_20160929_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extensionpackage',
            old_name='namespace',
            new_name='targetNamespace',
        ),
        migrations.RemoveField(
            model_name='templatepackage',
            name='namespace',
        ),
        migrations.AddField(
            model_name='extensionpackage',
            name='prefix',
            field=models.CharField(default='prefix', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='extensionpackage',
            name='schemaURL',
            field=models.URLField(default='schemaurl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='prefix',
            field=models.CharField(default='prefix', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='schemaURL',
            field=models.URLField(default='schemaURL'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='templatepackage',
            name='targetNamespace',
            field=models.CharField(default='targetNamespace', max_length=255),
            preserve_default=False,
        ),
    ]
