# Generated by Django 3.1.2 on 2020-10-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0011_templatepackage_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extensionpackage',
            name='nsmap',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='templatepackage',
            name='nsmap',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='templatepackage',
            name='structure',
            field=models.JSONField(default=list),
        ),
    ]
