# Generated by Django 3.1.2 on 2020-10-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0012_auto_20201014_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepackage',
            name='allElements',
            field=models.JSONField(null=True),
        ),
    ]
