# Generated by Django 5.0.3 on 2024-03-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileMaker', '0013_auto_20201023_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepackage',
            name='root_element',
            field=models.CharField(max_length=55),
        ),
    ]
