version: '3.3'

services:
  essarch:
    image: essarch
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_URL_ESSARCH:
      REDIS_URL_ESSARCH: redis://redis/1
      RABBITMQ_URL_ESSARCH: amqp://guest:guest@rabbitmq:5672
      ELASTICSEARCH_URL: http://elasticsearch:9200
      DJANGO_WATCHMAN_TIMEOUT: 60
    volumes:
      - ..:/code
      - /code/ESSArch.egg-info/
      - ./data:/ESSArch/data
      - ./config:/ESSArch/config
      - ./log:/ESSArch/log
      - /code/ESSArch_Core/frontend/static/frontend/build
    command:
      - /bin/bash
      - -c
      - |
        /code/docker/wait_for.sh ${DATABASE_HOST_ESSARCH} ${DATABASE_PORT_ESSARCH}
        /code/docker/wait_for.sh redis 6379
        /code/docker/wait_for.sh rabbitmq 5672
        /code/docker/wait_for.sh elasticsearch 9200
        /code/docker/docker-entrypoint.sh
    ports:
      - 8000:8000
    restart: on-failure
    tty: true
    depends_on:
      - ${DATABASE_SERVICE_ESSARCH}
      - rabbitmq
      - redis
      - elasticsearch
    networks:
      - essarch

  worker:
    image: essarch
    command:
      - /bin/bash
      - -c
      - |
        /code/docker/wait_for.sh redis 6379
        /code/docker/wait_for.sh rabbitmq 5672
        /code/docker/wait_for.sh essarch 8000
        /code/docker/wait_for.sh elasticsearch 9200
        essarch worker -l info -q celery,file_operation,validation
    environment:
      DATABASE_URL_ESSARCH:
      REDIS_URL_ESSARCH: redis://redis/1
      RABBITMQ_URL_ESSARCH: amqp://guest:guest@rabbitmq:5672
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ..:/code
      - /code/ESSArch.egg-info
      - ./data:/ESSArch/data
      - ./config:/ESSArch/config
      - ./log:/ESSArch/log
    tty: true
    depends_on:
      - essarch
      - rabbitmq
      - redis
      - elasticsearch
    networks:
      - essarch

  beat:
    image: essarch
    command:
      - /bin/bash
      - -c
      - |
        /code/docker/wait_for.sh redis 6379
        /code/docker/wait_for.sh rabbitmq 5672
        /code/docker/wait_for.sh essarch 8000
        /code/docker/wait_for.sh elasticsearch 9200
        essarch beat -l info
    environment:
      DATABASE_URL_ESSARCH:
      REDIS_URL_ESSARCH: redis://redis/1
      RABBITMQ_URL_ESSARCH: amqp://guest:guest@rabbitmq:5672
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ..:/code
      - /code/ESSArch.egg-info
      - ./data:/ESSArch/data
      - ./config:/ESSArch/config
      - ./log:/ESSArch/log
    tty: true
    depends_on:
      - essarch
      - rabbitmq
      - redis
      - elasticsearch
    networks:
      - essarch

  postgres:
    image: 'postgres'
    environment:
      POSTGRES_DB: essarch
      POSTGRES_USER: arkiv
      POSTGRES_PASSWORD: password
    volumes:
      - essarch_postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - essarch

  mariadb:
    image: 'mariadb:10.4.6'
    environment:
      MYSQL_DATABASE: essarch
      MYSQL_USER: arkiv
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - essarch_mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - essarch

  redis:
    image: 'redis'
    networks:
      - essarch
    ports:
      - 6379:6379

  rabbitmq:
    image: 'rabbitmq'
    ports:
      - 5672:5672
    networks:
      - essarch

  elasticsearch:
    build:
      context: elasticsearch
      args:
        ELK_VERSION: 6.5.4
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - essarch_elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      ES_JAVA_OPTS: '-Xmx256m -Xms256m'
    networks:
      - essarch

volumes:
  essarch_elasticsearch_data:
  essarch_mariadb_data:
  essarch_postgres_data:

networks:
  essarch:
    driver: bridge
