# Generated by Django 2.0.13 on 2019-03-28 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_auto_20190327_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentrelation',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='create date'),
        ),
    ]
