# Generated by Django 2.2 on 2019-04-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0028_tagversion_custom_fields'),
        ('agents', '0004_auto_20190328_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentidentifiertype',
            options={'verbose_name': 'agent identifier type', 'verbose_name_plural': 'agent identifier types'},
        ),
        migrations.AlterModelOptions(
            name='agentnametype',
            options={'verbose_name': 'agent name type', 'verbose_name_plural': 'agent name types'},
        ),
        migrations.AlterModelOptions(
            name='agentnotetype',
            options={'verbose_name': 'agent note type', 'verbose_name_plural': 'agent note types'},
        ),
        migrations.AlterModelOptions(
            name='agentplacetype',
            options={'verbose_name': 'agent place type', 'verbose_name_plural': 'agent place types'},
        ),
        migrations.AlterModelOptions(
            name='agentrelationtype',
            options={'verbose_name': 'agent relation type', 'verbose_name_plural': 'agent relation types'},
        ),
        migrations.AlterModelOptions(
            name='agenttaglinkrelationtype',
            options={'verbose_name': 'agent tag relation type', 'verbose_name_plural': 'agent tag relation types'},
        ),
        migrations.AlterModelOptions(
            name='agenttype',
            options={'verbose_name': 'agent type', 'verbose_name_plural': 'agent types'},
        ),
        migrations.AlterModelOptions(
            name='authoritytype',
            options={'verbose_name': 'authority type', 'verbose_name_plural': 'authority types'},
        ),
        migrations.AlterModelOptions(
            name='mainagenttype',
            options={'verbose_name': 'main agent type', 'verbose_name_plural': 'main agent types'},
        ),
        migrations.AlterUniqueTogether(
            name='agenttaglink',
            unique_together={('agent', 'tag')},
        ),
    ]
