# Generated by Django 2.0.13 on 2019-04-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20190407_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttype',
            name='legal_status',
            field=models.TextField(blank=True, verbose_name='legal status'),
        ),
    ]
