# Generated by Django 2.0.13 on 2019-04-26 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_auto_20190426_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenttype',
            name='main_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agents.MainAgentType', verbose_name='main type'),
        ),
    ]
