# Generated by Django 2.2.4 on 2019-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20190529_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentnametype',
            name='authority',
            field=models.BooleanField(default=False, verbose_name='authority'),
        ),
        migrations.AddField(
            model_name='agentnotetype',
            name='history',
            field=models.BooleanField(default=False, verbose_name='history'),
        ),
    ]
