# Generated by Django 2.2.5 on 2019-09-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_auto_20190902_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttype',
            name='creator',
            field=models.BooleanField(default=False, verbose_name='creator'),
        ),
    ]
