# Generated by Django 2.2.5 on 2019-09-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agenttype_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenttype',
            name='creator',
        ),
        migrations.AddField(
            model_name='agenttaglinkrelationtype',
            name='creator',
            field=models.BooleanField(default=False, verbose_name='creator'),
        ),
    ]
