# Generated by Django 3.0.2 on 2020-01-19 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_auto_20190925_1848'),
        ('i18n', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='i18n.Language', verbose_name='language'),
        )
    ]
