# Generated by Django 3.0.6 on 2020-09-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_auto_20200305_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='level_of_detail',
            field=models.IntegerField(choices=[(0, 'full'), (1, 'partial'), (2, 'minimal')], db_index=True, verbose_name='level of detail'),
        ),
    ]
