# Generated by Django 3.1.2 on 2020-10-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_auto_20200922_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentname',
            name='certainty',
            field=models.BooleanField(null=True, verbose_name='certainty'),
        ),
    ]
