# Generated by Django 3.1.2 on 2020-11-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_auto_20201014_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttaglinkrelationtype',
            name='date_render_format',
            field=models.CharField(blank=True, choices=[('yyyy', 'yyyy'), ('yyyy-MM-dd', 'yyyy-MM-dd')], max_length=255, verbose_name='Date render format'),
        ),
    ]
