# Generated by Django 5.2.5 on 2025-08-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_alter_agent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='related_agents',
            field=models.ManyToManyField(through='agents.AgentRelation', through_fields=('agent_a', 'agent_b'), to='agents.agent'),
        ),
    ]
