# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ip', '0064_informationpackage_appraisal_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[(b'archival_object', b'Archival Object'), (b'metadata', b'Metadata')], default=b'archival_object', max_length=100)),
                ('frequency', models.CharField(blank=True, default=b'', max_length=255)),
                ('specification', jsonfield.fields.JSONField(default=None, null=True)),
                ('information_packages', models.ManyToManyField(related_name='appraisal_rules', to='ip.InformationPackage')),

            ],
        ),
        migrations.CreateModel(
            name='AppraisalJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='maintenance.AppraisalRule')),
                ('status', models.CharField(choices=[(b'RECEIVED', b'RECEIVED'), (b'RETRY', b'RETRY'), (b'REVOKED', b'REVOKED'), (b'SUCCESS', b'SUCCESS'), (b'STARTED', b'STARTED'), (b'FAILURE', b'FAILURE'), (b'PENDING', b'PENDING')], default=b'PENDING', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AppraisalJobEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('document', models.CharField(blank=True, max_length=255)),
                ('component', models.CharField(blank=True, max_length=255)),
                ('component_field', models.CharField(blank=True, max_length=255)),
                ('ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_job_entries', to='ip.InformationPackage')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='maintenance.AppraisalJob')),
            ],
        ),
        migrations.AlterModelOptions(
            name='appraisaljob',
            options={'get_latest_by': 'start_date'},
        ),
    ]
