# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 02:43
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20180128_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionjob',
            options={'get_latest_by': 'start_date'},
        ),
    ]
