# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-29 03:48
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20180129_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisaljob',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='maintenance.AppraisalRule'),
        ),
        migrations.AlterField(
            model_name='conversionjob',
            name='rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='maintenance.ConversionRule'),
        ),
    ]
