# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-01 09:47
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_auto_20180531_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalrule',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conversionrule',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
