# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-07 14:54
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_auto_20180601_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalrule',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='conversionrule',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
