# Generated by Django 3.0.3 on 2020-02-13 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_auto_20190320_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalrule',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='conversionrule',
            name='frequency',
        ),
    ]
