# Generated by Django 3.0.3 on 2020-02-18 09:03

import ESSArch_Core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0085_remove_informationpackage_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0010_auto_20190320_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('package_file_pattern', ESSArch_Core.fields.JSONField(default=None, null=True)),
                ('public', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('archival_object', 'Archival Object'), ('metadata', 'Metadata')], default='archival_object', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConversionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('package_file_pattern', ESSArch_Core.fields.JSONField(default=None, null=True)),
                ('public', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='conversionrule',
            name='information_packages',
        ),
        migrations.RemoveField(
            model_name='conversionrule',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appraisaljob',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='conversionjob',
            name='rule',
        ),
        migrations.AddField(
            model_name='appraisaljob',
            name='information_packages',
            field=models.ManyToManyField(related_name='appraisal_jobs', to='ip.InformationPackage'),
        ),
        migrations.AddField(
            model_name='appraisaljob',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisaljob',
            name='package_file_pattern',
            field=ESSArch_Core.fields.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='information_packages',
            field=models.ManyToManyField(related_name='conversion_jobs', to='ip.InformationPackage'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='specification',
            field=ESSArch_Core.fields.JSONField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='AppraisalRule',
        ),
        migrations.DeleteModel(
            name='ConversionRule',
        ),
        migrations.AddField(
            model_name='appraisaljob',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='maintenance.AppraisalTemplate'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='maintenance.ConversionTemplate'),
        ),
    ]
