# Generated by Django 3.0.3 on 2020-02-18 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0079_auto_20200131_1649'),
        ('maintenance', '0011_auto_20200218_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisaljob',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_jobs', to='WorkflowEngine.ProcessTask'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_jobs', to='WorkflowEngine.ProcessTask'),
        ),
    ]
