# Generated by Django 3.0.3 on 2020-02-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0085_remove_informationpackage_policy'),
        ('maintenance', '0011_auto_20200213_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalrule',
            name='specification',
        ),
        migrations.RemoveField(
            model_name='conversionrule',
            name='specification',
        ),
        migrations.AddField(
            model_name='appraisaljob',
            name='information_packages',
            field=models.ManyToManyField(related_name='appraisal_jobs', to='ip.InformationPackage'),
        ),
        migrations.AddField(
            model_name='appraisaljob',
            name='package_file_pattern',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appraisalrule',
            name='package_file_pattern',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='information_packages',
            field=models.ManyToManyField(related_name='conversion_jobs', to='ip.InformationPackage'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='package_file_pattern',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversionrule',
            name='package_file_pattern',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
