# Generated by Django 3.0.3 on 2020-02-14 14:11

from ESSArch_Core.fields import JSONField
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ip', '0085_remove_informationpackage_policy'),
        ('maintenance', '0011_auto_20200213_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppraisalRule',
            new_name='AppraisalTemplate',
        ),
        migrations.RenameModel(
            old_name='ConversionRule',
            new_name='ConversionTemplate',
        ),
        migrations.RenameField(
            model_name='AppraisalTemplate',
            old_name='specification',
            new_name='package_file_pattern',
        ),
        migrations.RenameField(
            model_name='ConversionTemplate',
            old_name='specification',
            new_name='package_file_pattern',
        ),
        migrations.RemoveField(
            model_name='AppraisalTemplate',
            name='information_packages',
        ),
        migrations.RemoveField(
            model_name='ConversionTemplate',
            name='information_packages',
        ),
        migrations.RenameField(
            model_name='appraisaljob',
            old_name='rule',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='conversionjob',
            old_name='rule',
            new_name='template',
        ),
        migrations.AddField(
            model_name='appraisaljob',
            name='information_packages',
            field=models.ManyToManyField(related_name='appraisal_jobs', to='ip.InformationPackage'),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='information_packages',
            field=models.ManyToManyField(related_name='conversion_jobs', to='ip.InformationPackage'),
        ),
        migrations.AddField(
            model_name='appraisaljob',
            name='package_file_pattern',
            field=JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='package_file_pattern',
            field=JSONField(default=None, null=True),
        ),
    ]
