# Generated by Django 3.0.3 on 2020-02-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0065_remove_tag_appraisal_job'),
        ('maintenance', '0012_auto_20200218_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisaljob',
            name='tags',
            field=models.ManyToManyField(related_name='appraisal_jobs', to='tags.Tag'),
        ),
    ]
