# Generated by Django 3.0.3 on 2020-02-17 15:03

import ESSArch_Core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_auto_20200214_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversionjob',
            name='package_file_pattern',
        ),
        migrations.AddField(
            model_name='appraisaljob',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='label',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conversionjob',
            name='specification',
            field=ESSArch_Core.fields.JSONField(default=None, null=True),
        ),
    ]
