# Generated by Django 3.0.3 on 2020-02-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_appraisaljob_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversionjob',
            options={'get_latest_by': 'start_date', 'ordering': ('-start_date',), 'permissions': (('run_conversionjob', 'Can run conversion job'),)},
        ),
    ]
