# Generated by Django 3.0.3 on 2020-03-03 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_auto_20200228_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversiontemplate',
            old_name='package_file_pattern',
            new_name='specification',
        ),
    ]
