# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 15:30
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('view_pul', 'Can view PuL'),)},
        ),
    ]
