# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-09 13:53
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20171120_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('search', 'Can search'), ('view_pul', 'Can view PuL'))},
        ),
    ]
