# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 10:32
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20180308_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('version_link', models.UUIDField(default=uuid.uuid4)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'create_date',
            },
        ),
        migrations.CreateModel(
            name='TagStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tags.TagStructure')),
                ('structure', models.ForeignKey(limit_choices_to={'is_template': False}, on_delete=django.db.models.deletion.PROTECT, to='tags.Structure')),
            ],
            options={
                'get_latest_by': 'structure__create_date',
            },
        ),
        migrations.CreateModel(
            name='TagVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('elastic_index', models.CharField(default=None, max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='index',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='information_packages',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='link_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tree_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='version_end_date',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='version_start_date',
        ),
        migrations.AddField(
            model_name='tag',
            name='current_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_version_tags', to='tags.TagVersion'),
        ),
        migrations.AddField(
            model_name='tagversion',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='tagstructure',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='tags.Tag'),
        ),
    ]
