# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 10:04
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_auto_20180314_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('search', 'Can search'),)},
        ),
    ]
