# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 09:30
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_auto_20180316_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagstructure',
            options={'get_latest_by': 'structure__create_date', 'ordering': ('structure__create_date',)},
        ),
        migrations.AlterModelOptions(
            name='tagversion',
            options={'get_latest_by': 'create_date'},
        ),
    ]
