# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 13:17
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ip', '0070_auto_20180429_1427'),
        ('tags', '0007_auto_20180416_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='information_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='ip.InformationPackage'),
        ),
    ]
