# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-09 13:58
from django.db import migrations

from ESSArch_Core.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0011_auto_20180625_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='specification',
            field=JSONField(default={}),
        ),
    ]
