# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-17 10:54
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0014_auto_20181122_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureunit',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
