# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0016_auto_20190215_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelationType',
            new_name='AgentRelationType',
        ),
    ]
