# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0018_auto_20190221_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentnote',
            name='create_date',
            field=models.DateTimeField(verbose_name='create date'),
        ),
        migrations.AlterField(
            model_name='agentnote',
            name='revise_date',
            field=models.DateTimeField(null=True, verbose_name='revise date'),
        ),
    ]
