# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 14:47
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0019_auto_20190326_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structureunit',
            name='type_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.StructureUnitType'),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='type_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.TagVersionType'),
        ),
        migrations.RenameField(
            model_name='structureunit',
            old_name='type_link',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='tagversion',
            old_name='type_link',
            new_name='type',
        ),
    ]
