# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0019_auto_20190221_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrelation',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='create date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentrelation',
            name='revise_date',
            field=models.DateTimeField(auto_now=True, verbose_name='revise date'),
        ),
    ]
