# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-27 13:33
from django.db import migrations, models
import django.db.models.deletion


def create_temp_type(apps, schema_editor):
    Structure = apps.get_model('tags', 'Structure')
    StructureType = apps.get_model('tags', 'StructureType')

    if Structure.objects.exists():
        StructureType.objects.get_or_create(pk=1, defaults={'name': 'temp'})


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0021_tagversiontype_archive_type'),
    ]

    operations = [
        migrations.RunPython(create_temp_type, migrations.RunPython.noop),
        migrations.AddField(
            model_name='structure',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tags.StructureType'),
            preserve_default=False,
        ),
    ]
