# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-25 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0021_auto_20190222_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.TextField(verbose_name='identifier')),
                ('structure_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='tags.StructureUnit', verbose_name='structure unit')),
                ('tag_version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='tags.TagVersion', verbose_name='tag version')),
            ],
        ),
        migrations.CreateModel(
            name='NodeIdentifierType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='nodeidentifier',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.NodeIdentifierType', verbose_name='type'),
        ),
    ]
