# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-26 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0022_auto_20190225_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagversionrelation',
            name='tag_version_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_version_relations_a', to='tags.TagVersion'),
        ),
        migrations.AlterField(
            model_name='tagversionrelation',
            name='tag_version_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_version_relations_b', to='tags.TagVersion'),
        ),
    ]
