# Generated by Django 2.0.13 on 2019-03-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0023_auto_20190328_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagversion',
            name='import_date',
            field=models.DateTimeField(null=True),
        ),
    ]
