# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-01 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0023_auto_20190226_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='level_of_detail',
            field=models.IntegerField(choices=[(0, 'minimal'), (1, 'partial'), (2, 'full')], db_index=True, verbose_name='level of detail'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='record_status',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'final')], db_index=True, verbose_name='record status'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='script',
            field=models.IntegerField(choices=[(0, 'draft'), (1, 'final')], db_index=True, verbose_name='record status'),
        ),
        migrations.AlterField(
            model_name='agenttype',
            name='cpf',
            field=models.CharField(choices=[('corporatebody', 'corporate body'), ('person', 'person'), ('family', 'family')], db_index=True, max_length=20),
        ),
    ]
