# Generated by Django 2.0.13 on 2019-03-28 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0024_tagversion_import_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
