# Generated by Django 2.0.13 on 2019-03-28 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0025_auto_20190328_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagversion',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
