# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0025_auto_20190305_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='script',
            field=models.IntegerField(choices=[(0, 'latin')], db_index=True, verbose_name='script'),
        ),
    ]
