# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 13:22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0027_structure_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagversion',
            name='custom_fields',
            field=models.JSONField(default={}),
        ),
    ]
