# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-01 13:22
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0027_structure_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagversion',
            name='extra_data',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
