# Generated by Django 2.2 on 2019-04-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0028_tagversion_custom_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='template',
            new_name='is_template',
        ),
    ]
