# Generated by Django 2.2 on 2019-04-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0029_auto_20190407_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='is_template',
            field=models.BooleanField(verbose_name='is template'),
        ),
    ]
