# Generated by Django 2.0.13 on 2019-04-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0031_structure_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='published',
            field=models.BooleanField(default=False, verbose_name='published'),
        ),
    ]
