# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 12:47
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0033_auto_20190411_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureunit',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='tags.StructureUnit', verbose_name='template'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='tags.Structure', verbose_name='template'),
        ),
    ]
