# Generated by Django 2.0.13 on 2019-04-15 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0035_auto_20190415_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structuretype',
            options={'verbose_name': 'structure type', 'verbose_name_plural': 'structure types'},
        ),
        migrations.AlterModelOptions(
            name='structureunittype',
            options={'verbose_name': 'structure unit type', 'verbose_name_plural': 'structure unit types'},
        ),
        migrations.AlterField(
            model_name='structuretype',
            name='movable_instance_units',
            field=models.BooleanField(default=False, verbose_name='movable instance units'),
        ),
        migrations.AlterField(
            model_name='structureunittype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='structureunittype',
            name='structure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.StructureType', verbose_name='structure type'),
        ),
    ]
