# Generated by Django 2.0.13 on 2019-04-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0036_auto_20190415_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='editable_instance_units',
            field=models.BooleanField(default=False, verbose_name='editable instance units'),
        ),
    ]
