# Generated by Django 2.0.13 on 2019-04-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0039_auto_20190424_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structureunit',
            options={'permissions': (('add_structure_unit_instance', 'Can add structure unit instances'), ('change_structure_unit_instance', 'Can edit instances of structure units'), ('delete_structure_unit_instance', 'Can delete instances of structure units'), ('move_structure_unit_instance', 'Can move instances of structure units'))},
        ),
    ]
