# Generated by Django 2.0.13 on 2019-04-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0041_auto_20190424_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuretype',
            name='editable_instances',
            field=models.BooleanField(default=False, verbose_name='editable instances'),
        ),
    ]
