# Generated by Django 2.0.13 on 2019-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0042_auto_20190424_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='editable_instance_relations',
            field=models.BooleanField(default=False, verbose_name='editable instance relations'),
        ),
    ]
