# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 07:43
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0043_structuretype_editable_instance_relations'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuretype',
            name='instance_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='instance name'),
        ),
    ]
