# Generated by Django 2.0.13 on 2019-04-26 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0044_structuretype_instance_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='structureunit',
            options={'permissions': (('add_structureunit_instance', 'Can add structure unit instances'), ('change_structureunit_instance', 'Can change instances of structure units'), ('delete_structureunit_instance', 'Can delete instances of structure units'), ('move_structureunit_instance', 'Can move instances of structure units'))},
        ),
    ]
