# Generated by Django 2.0.13 on 2019-04-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0045_auto_20190426_1212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'permissions': (('search', 'Can search'), ('create_archive', 'Can create new archives'), ('change_archive', 'Can change archives'), ('delete_archive', 'Can delete archives'), ('change_tag_location', 'Can change tag location'))},
        ),
    ]
