# Generated by Django 2.0.13 on 2019-05-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0046_auto_20190426_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metricprofile',
            options={'verbose_name': 'location profile', 'verbose_name_plural': 'location profiles'},
        ),
    ]
