# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 08:43
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0047_auto_20190523_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tags.Delivery', verbose_name='delivery')),
            ],
        ),
        migrations.AddField(
            model_name='delivery',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.DeliveryType', verbose_name='type'),
        ),
        migrations.AddField(
            model_name='structureunit',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tags.Transfer', verbose_name='transfer'),
        ),
        migrations.AddField(
            model_name='tagversion',
            name='transfer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tags.Transfer', verbose_name='transfer'),
        ),
    ]
