# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 09:06
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0049_auto_20190529_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverytype',
            options={'verbose_name': 'delivery type', 'verbose_name_plural': 'delivery types'},
        ),
    ]
