# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-29 09:14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0050_auto_20190529_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='structureunit',
            name='transfer',
        ),
        migrations.RemoveField(
            model_name='tagversion',
            name='transfer',
        ),
        migrations.AddField(
            model_name='structureunit',
            name='transfers',
            field=models.ManyToManyField(to='tags.Transfer', verbose_name='transfers'),
        ),
        migrations.AddField(
            model_name='tagversion',
            name='transfers',
            field=models.ManyToManyField(to='tags.Transfer', verbose_name='transfers'),
        ),
    ]
