# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 12:54
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_auto_20190529_2331'),
        ('profiles', '0050_auto_20180829_1056'),
        ('tags', '0052_auto_20190529_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='producer_organization',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='agents.Agent'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='reference_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='submission_agreement',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='profiles.SubmissionAgreement'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='submitter_individual_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='submitter_individual_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='submitter_individual_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='submitter_organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='submitter_organization_main_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
