# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 13:14
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0053_auto_20190612_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
