# Generated by Django 2.2.5 on 2019-09-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0054_transfer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='is_editable',
            field=models.BooleanField(default=True, verbose_name='is editable'),
        ),
    ]
