# Generated by Django 2.2.5 on 2019-09-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0055_structure_is_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
