# Generated by Django 2.2.5 on 2019-09-09 14:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0056_auto_20190909_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureRelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('mirrored_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tags.StructureRelationType', verbose_name='mirrored type')),
            ],
            options={
                'verbose_name': 'structure relation type',
                'verbose_name_plural': 'structure relation types',
            },
        ),
        migrations.CreateModel(
            name='StructureRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('start_date', models.DateField(null=True, verbose_name='start date')),
                ('end_date', models.DateField(null=True, verbose_name='end date')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create date')),
                ('revise_date', models.DateTimeField(auto_now=True, verbose_name='revise date')),
                ('structure_a', models.ForeignKey(limit_choices_to={'is_template': True}, on_delete=django.db.models.deletion.CASCADE, related_name='structure_relations_a', to='tags.Structure')),
                ('structure_b', models.ForeignKey(limit_choices_to={'is_template': True}, on_delete=django.db.models.deletion.CASCADE, related_name='structure_relations_b', to='tags.Structure')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tags.StructureRelationType')),
            ],
            options={
                'unique_together': {('structure_a', 'structure_b', 'type')},
            },
        ),
        migrations.AddField(
            model_name='structure',
            name='related_structures',
            field=models.ManyToManyField(through='tags.StructureRelation', to='tags.Structure'),
        ),
    ]
