# Generated by Django 2.2.5 on 2019-09-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0057_auto_20190909_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagversiontype',
            name='information_package_type',
            field=models.BooleanField(default=False, verbose_name='information package type'),
        ),
    ]
