# Generated by Django 2.2.5 on 2019-09-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0058_tagversiontype_information_package_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
