# Generated by Django 2.2.5 on 2019-09-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0060_auto_20190912_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='structure',
            name='published_date',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='reference_code',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
