# Generated by Django 2.2.5 on 2019-10-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0061_auto_20190920_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodenotetype',
            name='history',
            field=models.BooleanField(default=False, verbose_name='history'),
        ),
    ]
