# Generated by Django 2.2.6 on 2019-10-15 11:56

from django.db import migrations

from ESSArch_Core.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0062_nodenotetype_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagversiontype',
            name='custom_fields_template',
            field=JSONField(blank=True, default=[]),
        ),
    ]
