# Generated by Django 3.0.3 on 2020-02-18 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20200218_1003'),
        ('tags', '0063_tagversiontype_custom_fields_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='appraisal_job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='maintenance.AppraisalJob'),
        ),
        migrations.AddField(
            model_name='tag',
            name='flagged_for_appraisal',
            field=models.BooleanField(default=False),
        ),
    ]
