# Generated by Django 3.0.3 on 2020-02-24 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0064_auto_20200218_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='appraisal_job',
        ),
    ]
