# Generated by Django 3.0.3 on 2020-03-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0064_security_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='appraisal_date',
            field=models.DateTimeField(null=True),
        ),
    ]
