# Generated by Django 3.0.3 on 2020-02-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0065_remove_tag_appraisal_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='flagged_for_appraisal',
        ),
        migrations.AddField(
            model_name='tag',
            name='appraisal_date',
            field=models.DateTimeField(null=True),
        ),
    ]
