# Generated by Django 3.0.4 on 2020-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0066_auto_20200505_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureunittype',
            name='date_render_format',
            field=models.CharField(blank=True, choices=[('yyyy', 'yyyy'), ('yyyyMM', 'yyyyMM')], max_length=255, verbose_name='Date render format'),
        ),
        migrations.AddField(
            model_name='tagversiontype',
            name='date_render_format',
            field=models.CharField(blank=True, max_length=255, verbose_name='Date render format'),
        ),
    ]
