# Generated by Django 3.0.7 on 2020-09-03 13:40

import ESSArch_Core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0067_auto_20200613_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='structureunit',
            name='specification',
            field=ESSArch_Core.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='structureunittype',
            name='date_render_format',
            field=models.CharField(blank=True, choices=[('yyyy', 'yyyy'), ('yyyy-MM-dd', 'yyyy-MM-dd')], max_length=255, verbose_name='Date render format'),
        ),
        migrations.AlterField(
            model_name='tagversiontype',
            name='date_render_format',
            field=models.CharField(blank=True, choices=[('yyyy', 'yyyy'), ('yyyy-MM-dd', 'yyyy-MM-dd')], max_length=255, verbose_name='Date render format'),
        ),
    ]
