# Generated by Django 3.1.2 on 2020-10-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0068_auto_20200922_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='specification',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tagversion',
            name='custom_fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tagversiontype',
            name='custom_fields_template',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
