# Generated by Django 3.0.10 on 2020-10-21 10:53

import ESSArch_Core.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0068_auto_20200922_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rendering',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, choices=[('stylesheet', 'stylesheet')], max_length=255, verbose_name='Type')),
                ('file', models.FileField(upload_to='uploads/')),
                ('custom_fields', ESSArch_Core.fields.JSONField(default={})),
            ],
        ),
        migrations.AddField(
            model_name='tagversion',
            name='rendering',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_versions', to='tags.Rendering'),
        ),
    ]
