# Generated by Django 3.1.2 on 2020-10-22 22:37

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0069_auto_20201014_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagversion',
            name='custom_fields',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
