# Generated by Django 3.1.2 on 2020-10-25 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0070_auto_20201023_0037'),
        ('tags', '0069_auto_20201021_1253'),
    ]

    operations = [
    ]
