# Generated by Django 5.2.5 on 2025-08-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0079_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='related_structures',
            field=models.ManyToManyField(through='tags.StructureRelation', through_fields=('structure_a', 'structure_b'), to='tags.structure'),
        ),
        migrations.AlterField(
            model_name='structureunit',
            name='related_structure_units',
            field=models.ManyToManyField(through='tags.StructureUnitRelation', through_fields=('structure_unit_a', 'structure_unit_b'), to='tags.structureunit'),
        ),
    ]
