# Generated by Django 5.2.7 on 2025-10-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0080_alter_structure_related_structures_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagversion',
            name='elastic_index',
            field=models.CharField(db_index=True, default=None, max_length=255),
        ),
    ]
