# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_aip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileAIP'),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileClassification'),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileContentType'),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_data_selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileDataSelection'),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_dip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileDIP'),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileImport'),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_sip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileSIP'),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_submit_description',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileSubmitDescription'),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_transfer_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileTransferProject'),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profile_workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.ProfileWorkflow'),
        ),
    ]
