# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 12:16
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20160824_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilesip',
            name='sip_specification',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
