# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 13:38
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20160826_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesip',
            name='sip_template',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='profilesip',
            name='sip_specification_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
