"""
    ESSArch is an open source archiving and digital preservation system

    ESSArch
    Copyright (C) 2005-2019 ES Solutions AB

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program. If not, see <https://www.gnu.org/licenses/>.

    Contact information:
    Web - http://www.essolutions.se
    Email - essarch@essolutions.se
"""

# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:23
import uuid

from django.db import migrations, models

from ESSArch_Core.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(choices=[('transfer_project', 'Transfer Project'), ('content_type', 'Content Type'), ('data_selection', 'Data Selection'), ('classification', 'Classification'), ('import', 'Import'), ('submit_description', 'Submit Description'), ('sip', 'SIP'), ('aip', 'AIP'), ('dip', 'DIP'), ('workflow', 'Workflow'), ('preservation_description', 'Preservation Description')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('representation_info', models.CharField(blank=True, max_length=255)),
                ('preservation_descriptive_info', models.CharField(blank=True, max_length=255)),
                ('supplemental', models.CharField(blank=True, max_length=255)),
                ('access_constraints', models.CharField(blank=True, max_length=255)),
                ('datamodel_reference', models.CharField(blank=True, max_length=255)),
                ('additional', models.CharField(blank=True, max_length=255)),
                ('submission_method', models.CharField(blank=True, max_length=255)),
                ('submission_schedule', models.CharField(blank=True, max_length=255)),
                ('submission_data_inventory', models.CharField(blank=True, max_length=255)),
                ('structure', models.TextField()),
                ('template', JSONField(null=True)),
                ('specification', JSONField(null=True)),
                ('specification_data', JSONField(null=True)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Profile',
            },
        ),
    ]
