# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20160830_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, b'Disabled'), (1, b'Enabled'), (2, b'Default')], default=0, verbose_name=b'Profile status')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'ordering': ['status'],
                'verbose_name': 'ProfileRel',
            },
        ),
        migrations.RemoveField(
            model_name='profileaiprel',
            name='profileaip',
        ),
        migrations.RemoveField(
            model_name='profileaiprel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profileclassificationrel',
            name='profileclassification',
        ),
        migrations.RemoveField(
            model_name='profileclassificationrel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profilecontenttyperel',
            name='profilecontenttype',
        ),
        migrations.RemoveField(
            model_name='profilecontenttyperel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profiledataselectionrel',
            name='profiledataselection',
        ),
        migrations.RemoveField(
            model_name='profiledataselectionrel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profilediprel',
            name='profiledip',
        ),
        migrations.RemoveField(
            model_name='profilediprel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profileimportrel',
            name='profileimport',
        ),
        migrations.RemoveField(
            model_name='profileimportrel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profilepreservationmetadatarel',
            name='profilepreservationmetadata',
        ),
        migrations.RemoveField(
            model_name='profilepreservationmetadatarel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profilesiprel',
            name='profilesip',
        ),
        migrations.RemoveField(
            model_name='profilesiprel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profilesubmitdescriptionrel',
            name='profilesubmitdescription',
        ),
        migrations.RemoveField(
            model_name='profilesubmitdescriptionrel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profiletransferprojectrel',
            name='profiletransferproject',
        ),
        migrations.RemoveField(
            model_name='profiletransferprojectrel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='profileworkflowrel',
            name='profileworkflow',
        ),
        migrations.RemoveField(
            model_name='profileworkflowrel',
            name='submissionagreement',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_aip',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_classification',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_content_type',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_data_selection',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_dip',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_import',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_preservation_metadata',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_sip',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_submit_description',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_transfer_project',
        ),
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_workflow',
        ),
        migrations.DeleteModel(
            name='ProfileAIPRel',
        ),
        migrations.DeleteModel(
            name='ProfileClassificationRel',
        ),
        migrations.DeleteModel(
            name='ProfileContentTypeRel',
        ),
        migrations.DeleteModel(
            name='ProfileDataSelectionRel',
        ),
        migrations.DeleteModel(
            name='ProfileDIPRel',
        ),
        migrations.DeleteModel(
            name='ProfileImportRel',
        ),
        migrations.DeleteModel(
            name='ProfilePreservationMetadataRel',
        ),
        migrations.DeleteModel(
            name='ProfileSIPRel',
        ),
        migrations.DeleteModel(
            name='ProfileSubmitDescriptionRel',
        ),
        migrations.DeleteModel(
            name='ProfileTransferProjectRel',
        ),
        migrations.DeleteModel(
            name='ProfileWorkflowRel',
        ),
        migrations.AddField(
            model_name='profilerel',
            name='submissionagreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.SubmissionAgreement'),
        ),
        migrations.AddField(
            model_name='submissionagreement',
            name='profiles',
            field=models.ManyToManyField(related_name='submission_agreements', through='profiles.ProfileRel', to='profiles.Profile'),
        ),
    ]
