# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20160905_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilerel',
            options={'base_manager_name': 'objects', 'ordering': ['status'], 'verbose_name': 'ProfileRel'},
        ),
    ]
