# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 19:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields

def forwards_func(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    db_alias = schema_editor.connection.alias

    Profile.objects.using(db_alias).all().update(structure={})

def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20160905_1900'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='profile',
            name='structure',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
