# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20160906_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilerel',
            old_name='submissionagreement',
            new_name='submission_agreement',
        ),
    ]
