# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 13:47
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20160913_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='schemas',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
