# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20161011_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cm_change_authority',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cm_change_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cm_release_date',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cm_sections_affected',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cm_version',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
