# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 17:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_auto_20161107_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileip',
            name='LockedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='profiles',
            field=models.ManyToManyField(related_name='submission_agreements', through='profiles.ProfileSA', to='profiles.Profile'),
        ),
    ]
