# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_remove_submissionagreement_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilerel',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profilerel',
            name='submission_agreement',
        ),
        migrations.AlterField(
            model_name='profilesa',
            name='LockedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProfileRel',
        ),
    ]
