# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20161107_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileip',
            name='included',
            field=models.BooleanField(default=True),
        ),
    ]
