# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20161122_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileip',
            name='included',
            field=models.BooleanField(default=False),
        ),
    ]
