# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-15 20:29
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_auto_20161123_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='schemas',
            field=jsonfield.fields.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specification',
            field=jsonfield.fields.JSONField(default={}, blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specification_data',
            field=jsonfield.fields.JSONField(default={}, blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='structure',
            field=jsonfield.fields.JSONField(default={}, blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=jsonfield.fields.JSONField(default={}, blank=True),
        ),
    ]
