# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 10:23
from django.db import migrations

from ESSArch_Core.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20170315_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionagreement',
            name='template',
            field=JSONField(default={}),
        ),
    ]
