# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 10:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20170425_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionagreement',
            name='template',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
