# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 14:49
from django.db import migrations

from ESSArch_Core.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0029_submissionagreement_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionagreement',
            name='template',
            field=JSONField(default=[]),
        ),
    ]
