# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-22 08:01
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20170428_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissionagreement',
            options={'ordering': ['name'], 'permissions': (('create_new_sa_generation', 'Can create new generations of SA'),), 'verbose_name': 'Submission Agreement'},
        ),
    ]
