# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-02 14:55
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0032_auto_20170802_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionagreement',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
