# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0033_submissionagreement_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_individual_additional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_individual_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_individual_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_individual_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_individual_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_main_additional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_main_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_main_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_main_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_main_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='archivist_organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='cm_change_authority',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='cm_change_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='cm_release_date',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='cm_sections_affected',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='cm_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='designated_community_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='designated_community_individual_additional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='designated_community_individual_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='designated_community_individual_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='designated_community_individual_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='designated_community_individual_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_individual_additional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_individual_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_individual_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_individual_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_individual_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_main_additional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_main_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_main_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_main_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_main_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='producer_organization',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
