# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-17 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_auto_20170817_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileipdata',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_versions', to='profiles.ProfileIP'),
        ),
    ]
