# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-24 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0037_auto_20170817_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileipdata',
            options={'ordering': ['version'], 'permissions': (('profile_management', 'Can manage profiles'),)},
        ),
    ]
