# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-05 12:48
from django.db import migrations

from ESSArch_Core.fields import JSONField


def forwards_func(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    db_alias = schema_editor.connection.alias

    for p in Profile.objects.using(db_alias).iterator():
        if p.structure == {}:
            p.structure = []
        if p.template == {}:
            p.template = []

        p.save(update_fields=['structure', 'template'])

def reverse_func(apps, schema_editor):
    Profile = apps.get_model("profiles", "Profile")
    db_alias = schema_editor.connection.alias

    for p in Profile.objects.using(db_alias).iterator():
        if p.structure == []:
            p.structure = {}
        if p.template == []:
            p.template = {}

        p.save(update_fields=['structure', 'template'])


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0035_auto_20170817_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='structure',
            field=JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=JSONField(blank=True, default=[]),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
