# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 13:28
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0039_auto_20170905_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionagreement',
            name='profile_aip_description',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aip_description_sa', to='profiles.Profile'),
        ),
    ]
