# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-27 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0041_submissionagreement_profile_aic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[(b'transfer_project', b'Transfer Project'), (b'content_type', b'Content Type'), (b'data_selection', b'Data Selection'), (b'authority_information', b'Authority Information'), (b'archival_description', b'Archival Description'), (b'import', b'Import'), (b'submit_description', b'Submit Description'), (b'sip', b'SIP'), (b'aic_description', b'AIC Description'), (b'aip', b'AIP'), (b'aip_description', b'AIP Description'), (b'dip', b'DIP'), (b'workflow', b'Workflow'), (b'preservation_metadata', b'Preservation Metadata'), (b'event', b'Event')], max_length=255),
        ),
    ]
