# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 20:23
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0042_auto_20170927_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionagreement',
            name='profile_mediaconch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediaconch_sa', to='profiles.Profile'),
        ),
    ]
