# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 18:48
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_submissionagreement_profile_mediaconch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_mediaconch',
        ),
        migrations.AddField(
            model_name='submissionagreement',
            name='profile_validation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_sa', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('transfer_project', 'Transfer Project'), ('content_type', 'Content Type'), ('data_selection', 'Data Selection'), ('authority_information', 'Authority Information'), ('archival_description', 'Archival Description'), ('import', 'Import'), ('submit_description', 'Submit Description'), ('sip', 'SIP'), ('aic_description', 'AIC Description'), ('aip', 'AIP'), ('aip_description', 'AIP Description'), ('dip', 'DIP'), ('workflow', 'Workflow'), ('preservation_metadata', 'Preservation Metadata'), ('event', 'Event'), ('validation', 'Validation')], max_length=255),
        ),
    ]
