# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20171203_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionagreement',
            name='profile_transformation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transformation_sa', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[(b'transfer_project', b'Transfer Project'), (b'content_type', b'Content Type'), (b'data_selection', b'Data Selection'), (b'authority_information', b'Authority Information'), (b'archival_description', b'Archival Description'), (b'import', b'Import'), (b'submit_description', b'Submit Description'), (b'sip', b'SIP'), (b'aic_description', b'AIC Description'), (b'aip', b'AIP'), (b'aip_description', b'AIP Description'), (b'dip', b'DIP'), (b'workflow', b'Workflow'), (b'preservation_metadata', b'Preservation Metadata'), (b'event', b'Event'), (b'validation', b'Validation'), (b'transformation', b'Transformation')], max_length=255),
        ),
    ]
