# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-24 15:07
from django.db import migrations, models
import django.db.models.deletion

from ESSArch_Core.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0046_auto_20180128_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileIPDataTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data', JSONField(default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
