# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-18 16:41
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0047_profileipdatatemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submissionagreement',
            name='profile_transformation',
        ),
    ]
