# Generated by Django 2.2.7 on 2019-11-22 08:44

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from ESSArch_Core.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ip', '0083_auto_20191015_2358'),
        ('profiles', '0051_auto_20190611_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionAgreementIPData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', JSONField(default={})),
                ('version', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('information_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ip.InformationPackage')),
                ('submission_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.SubmissionAgreement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['version'],
                'unique_together': {('submission_agreement', 'information_package', 'version')},
            },
        ),
    ]
