# Generated by Django 2.2.8 on 2019-12-15 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0053_submissionagreement_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionagreement',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_agreements', to='configuration.StoragePolicy'),
        ),
    ]
