# Generated by Django 3.1.2 on 2020-10-14 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0055_non_nullable_sa_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='schemas',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specification',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='specification_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='structure',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profile',
            name='template',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='profileipdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profileipdatatemplate',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='template',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='submissionagreementipdata',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
