# Generated by Django 3.1.2 on 2021-02-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0056_auto_20201014_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('action_workflow', 'Action Workflow'), ('transfer_project', 'Transfer Project'), ('content_type', 'Content Type'), ('data_selection', 'Data Selection'), ('authority_information', 'Authority Information'), ('archival_description', 'Archival Description'), ('import', 'Import'), ('submit_description', 'Submit Description'), ('sip', 'SIP'), ('aic_description', 'AIC Description'), ('aip', 'AIP'), ('aip_description', 'AIP Description'), ('dip', 'DIP'), ('workflow', 'Workflow'), ('preservation_metadata', 'Preservation Metadata'), ('event', 'Event'), ('validation', 'Validation')], max_length=255),
        ),
    ]
