# Generated by Django 3.1.2 on 2021-04-12 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0057_auto_20210225_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionagreement',
            name='profile_action_workflow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_workflow_sa', to='profiles.profile'),
        ),
    ]
