# Generated by Django 3.1.2 on 2021-07-13 18:39

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0058_submissionagreement_profile_action_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileipdata',
            name='extra_paths_to_parse',
            field=picklefield.fields.PickledObjectField(default=list, editable=False),
        ),
        migrations.AddField(
            model_name='profileipdata',
            name='parsed_files',
            field=picklefield.fields.PickledObjectField(default=list, editable=False),
        ),
    ]
