# Generated by Django 3.1.2 on 2021-09-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0059_auto_20210713_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionagreement',
            name='overall_submission_agreement',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
