# Generated by Django 3.2.7 on 2021-10-19 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0025_auto_20210126_1600'),
        ('profiles', '0060_submissionagreement_overall_submission_agreement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionagreement',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_agreements', to='configuration.storagepolicy', verbose_name='storage policy'),
        ),
    ]
