# Generated by Django 3.2.15 on 2022-09-13 20:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0026_alter_storagepolicy_ingest_path'),
        ('profiles', '0061_alter_submissionagreement_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionagreement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submissionagreement',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submission_agreements', to='configuration.storagepolicy', verbose_name='storage policy'),
        ),
    ]
