# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='message',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
