# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-24 17:20
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0004_validation_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
