# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-12 11:25
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkflowEngine', '0001_initial'),
        ('fixity', '0005_validation_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='WorkflowEngine.ProcessTask'),
        ),
    ]
