# Generated by Django 3.0.3 on 2020-03-03 14:14

import ESSArch_Core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0006_validation_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('APP', 'Application'), ('PY_MOD', 'Python Module'), ('DOCKER_IMG', 'Docker Image')], max_length=20)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('path', models.TextField()),
                ('cmd', models.TextField()),
                ('enabled', models.BooleanField()),
                ('form', ESSArch_Core.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
