# Generated by Django 3.0.4 on 2020-05-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0007_conversiontool'),
    ]

    operations = [
        migrations.RenameModel('ConversionTool', 'ActionTool')
    ]
