# Generated by Django 3.0.3 on 2020-03-03 14:53

import ESSArch_Core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0007_conversiontool'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversiontool',
            options={'verbose_name': 'conversion tool', 'verbose_name_plural': 'conversion tools'},
        ),
        migrations.AlterField(
            model_name='conversiontool',
            name='cmd',
            field=models.TextField(verbose_name='command'),
        ),
        migrations.AlterField(
            model_name='conversiontool',
            name='enabled',
            field=models.BooleanField(verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='conversiontool',
            name='form',
            field=ESSArch_Core.fields.JSONField(blank=True, null=True, verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='conversiontool',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='conversiontool',
            name='path',
            field=models.TextField(verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='conversiontool',
            name='type',
            field=models.CharField(choices=[('APP', 'Application'), ('PY_MOD', 'Python Module'), ('DOCKER_IMG', 'Docker Image')], max_length=20, verbose_name='type'),
        ),
    ]
