# Generated by Django 3.0.4 on 2020-05-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0009_auto_20200518_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontool',
            name='docker',
        ),
        migrations.AddField(
            model_name='actiontool',
            name='environment',
            field=models.CharField(choices=[('cli', 'Cli Env'), ('python', 'Python Env'), ('docker', 'Docker Env')], default='cli', max_length=20, verbose_name='environment'),
        ),
    ]
