# Generated by Django 3.0.6 on 2020-09-22 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0010_auto_20200519_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontool',
            name='delete_original',
            field=models.BooleanField(default=False, verbose_name='remove orginal file after processing'),
        ),
    ]
