# Generated by Django 3.1.2 on 2020-10-14 17:16

import ESSArch_Core.fixity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0011_actiontool_delete_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontool',
            name='form',
            field=models.JSONField(blank=True, default=ESSArch_Core.fixity.models.ActionTool_form_default, null=True, verbose_name='form'),
        ),
        migrations.AlterField(
            model_name='validation',
            name='passed',
            field=models.BooleanField(null=True),
        ),
    ]
