# Generated by Django 3.1.2 on 2021-02-25 20:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0012_auto_20201014_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontool',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='actiontool',
            name='file',
            field=models.FileField(null=True, upload_to='stylesheets/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xslt'])]),
        ),
    ]
