# Generated by Django 3.1.2 on 2021-04-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0014_auto_20210402_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actiontool',
            name='file',
        ),
    ]
