# Generated by Django 3.1.2 on 2021-04-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixity', '0015_remove_actiontool_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validation',
            options={'get_latest_by': ['time_done']},
        ),
    ]
